# AUTO-GENERATED KAGGLE BUNDLE — GalaxyNet V25 Cascade Pipeline
# This file merges modular components for Kaggle compatibility.
# Generated by scripts/consolidate.py

from __future__ import annotations

import argparse
import datetime
import gc
import json
import math
import multiprocessing
import os
import pickle
import random
import subprocess
import sys
import time
import zipfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Tuple

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import (
    brier_score_loss,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split

try:
    import tensorflow_addons as tfa
except Exception:
    tfa = None

try:
    import xgboost as xgb
except ImportError:
    xgb = None

# ============================================================
# START OF config.py
# ============================================================




@dataclass
class Config:
    # ── Paths ──────────────────────────────────────────────────
    kaggle_input_dir: Path = Path('/kaggle/input/galaxy-zoo-the-galaxy-challenge')
    kaggle_temp_dir: Path = Path('/kaggle/temp')
    output_dir: Path = Path('/kaggle/working/outputs')

    # ── Image resolution curriculum ────────────────────────────
    image_size_phase1: int = 128
    image_size_phase2: int = 192
    image_size_phase3: int = 384
    center_crop_ratio: float = 0.75

    # ── Batch sizes (BASE per device) ──────────────────────────
    batch_size_phase1: int = 16
    batch_size_phase2: int = 8
    batch_size_phase3: int = 4
    grad_accumulation_steps: int = 1

    # ── Data split ─────────────────────────────────────────────
    seed: int = 42
    val_split: float = 0.15
    test_split: float = 0.10

    # ── Model Architecture ─────────────────────────────────────
    architecture: str = 'EfficientNetV2B2'
    multi_view: bool = True

    # ── Training Schedule (MINIMUM FOR TESTING) ────────────────
    warmup_epochs: int = 1
    midtune_epochs: int = 1
    finetune_epochs: int = 1

    warmup_lr: float = 2e-4
    midtune_lr: float = 2e-5
    finetune_lr: float = 5e-6

    unfreeze_phase2: int = 50
    unfreeze_phase3: int = 100

    # ── Augmentation ───────────────────────────────────────────
    mixup_alpha: float = 0.4
    mixup_prob: float = 0.5
    cutout_n_holes: int = 2
    cutout_max_size_ratio: float = 0.20

    # ── Astronomy-Specific Augmentations (V26) ─────────────────
    augment_poisson_scale: float = 25.0
    augment_poisson_prob: float = 0.3
    augment_blur_prob: float = 0.2
    augment_blur_sigma_range: Tuple[float, float] = (0.5, 2.0)

    # ── SWA ────────────────────────────────────────────────────
    swa_epochs: int = 1  # Minimum
    swa_lr_high: float = 1e-5
    swa_lr_low: float = 2e-6

    # ── TTA ────────────────────────────────────────────────────
    tta_n_augments: int = 2 # Minimum

    # ── Runtime ────────────────────────────────────────────────
    enable_mixed_precision: bool = True

    def get_scaled_batch_size(self, base_size: int, strategy: tf.distribute.Strategy) -> int:
        return base_size * strategy.num_replicas_in_sync


# ============================================================
# START OF utils.py
# ============================================================






def set_global_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)


def get_strategy() -> tf.distribute.Strategy:
    """Detect and initialize the appropriate distribution strategy."""
    try:
        # Standard TPU detection
        tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
        tf.config.experimental_connect_to_cluster(tpu)
        tf.tpu.experimental.initialize_tpu_system(tpu)
        strategy = tf.distribute.TPUStrategy(tpu)
        print(f"Running on TPU (Standard): {tpu.cluster_spec().as_dict()}")
        return strategy
    except (ValueError, RuntimeError, tf.errors.NotFoundError):
        try:
            # Fallback for some Kaggle environments (TPU v5 or newer)
            tpu = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='local')
            tf.config.experimental_connect_to_cluster(tpu)
            tf.tpu.experimental.initialize_tpu_system(tpu)
            strategy = tf.distribute.TPUStrategy(tpu)
            print("Running on TPU (Local Resolver)")
            return strategy
        except (ValueError, RuntimeError, tf.errors.NotFoundError):
            gpus = tf.config.list_physical_devices('GPU')
            if gpus:
                print(f"Running on GPU: {len(gpus)} device(s)")
                return tf.distribute.MirroredStrategy()
            else:
                print("Running on CPU")
                return tf.distribute.get_strategy()


def setup_environment(config: Config) -> None:
    set_global_seed(config.seed)

    if config.enable_mixed_precision:
        # Determine policy based on ACTUAL hardware presence
        # TPU v3/v5 prefers bfloat16, GPU prefers float16
        is_tpu = any(os.environ.get(k) for k in ['TPU_NAME', 'KAGGLE_TPU_ADDR', 'COLAB_TPU_ADDR'])

        policy = 'mixed_bfloat16' if is_tpu else 'mixed_float16'
        tf.keras.mixed_precision.set_global_policy(policy)
        print(f"Hardware-aware mixed precision policy set to: {policy}")

    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)

    # Final check for visibility
    if not any(os.environ.get(k) for k in ['TPU_NAME', 'KAGGLE_TPU_ADDR']) and not gpus:
        print('Warning: No Hardware Accelerator (GPU/TPU) detected — running on CPU')


def find_kaggle_file(root: Path, name: str) -> Path:
    matches = list(root.rglob(name))
    if not matches:
        raise FileNotFoundError(f'Could not find {name} under {root}')
    return matches[0]


def _extract_zip_if_needed(zip_path: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(output_dir)


def setup_kaggle_environment(config: Config) -> Tuple[Path, Path]:
    # Look for files more broadly if not found in specific path
    search_roots = [config.kaggle_input_dir, Path('/kaggle/input')]

    def find_robustly(name: str):
        for root in search_roots:
            if not root.exists(): continue
            try:
                return find_kaggle_file(root, name)
            except FileNotFoundError:
                continue
        raise FileNotFoundError(f"Could not find {name} in any of {search_roots}")

    # Try to find CSV directly first (if already unzipped)
    try:
        csv_path = find_robustly('training_solutions_rev1.csv')
    except FileNotFoundError:
        # If not, find and extract zip
        train_csv_zip = find_robustly('training_solutions_rev1.zip')
        _extract_zip_if_needed(train_csv_zip, config.kaggle_temp_dir)
        csv_path = find_kaggle_file(config.kaggle_temp_dir, 'training_solutions_rev1.csv')

    # Try to find image dir directly
    try:
        # Check for a few jpgs to confirm it's the right dir
        image_dir_candidate = find_robustly('images_training_rev1')
        if not image_dir_candidate.is_dir():
             # maybe it's the zip name, try to find a subfolder
             raise FileNotFoundError
        csv_path_check = list(Path(image_dir_candidate).glob('*.jpg'))
        if len(csv_path_check) < 10:
             raise FileNotFoundError
        image_dir = image_dir_candidate
    except FileNotFoundError:
        # If not, find and extract zip
        image_zip = find_robustly('images_training_rev1.zip')
        _extract_zip_if_needed(image_zip, config.kaggle_temp_dir)
        image_dir = find_kaggle_file(config.kaggle_temp_dir, 'images_training_rev1')

    return Path(csv_path), Path(image_dir)


def save_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2, default=str)


def is_kaggle_runtime() -> bool:
    return os.environ.get('KAGGLE_KERNEL_RUN_TYPE') is not None


# ══════════════════════════════════════════════════════════════
# V25 — GRADIENT ACCUMULATION HELPER
# ══════════════════════════════════════════════════════════════

@tf.keras.utils.register_keras_serializable(package="Custom")
class GradientAccumulationModel(tf.keras.Model):
    """Wrapper model that accumulates gradients over N mini-batches
    before applying an optimizer step. This allows effective large
    batch sizes when VRAM is limited (e.g., batch_size=16 × accum=2 = 32 effective).

    Usage:
        ga_model = GradientAccumulationModel(base_model, accumulation_steps=2)
        ga_model.compile(optimizer=..., loss=..., metrics=...)
        ga_model.fit(train_ds, ...)
    """

    def __init__(self, inner_model: tf.keras.Model, accumulation_steps: int = 2, **kwargs):
        super().__init__(**kwargs)
        self.inner_model = inner_model
        self.accumulation_steps = accumulation_steps
        self.step_count = tf.Variable(0, trainable=False, dtype=tf.int32)
        self._accum_gradients = None

    def get_config(self):
        config = super().get_config()
        config.update({
            "inner_model": self.inner_model,
            "accumulation_steps": self.accumulation_steps,
        })
        return config

    def call(self, inputs, training=False):
        return self.inner_model(inputs, training=training)

    @property
    def trainable_variables(self):
        return self.inner_model.trainable_variables

    def train_step(self, data):
        if len(data) == 3:
            x, y, sample_weight = data
        else:
            x, y = data
            sample_weight = None

        # Initialize gradient accumulators on first call
        if self._accum_gradients is None:
            self._accum_gradients = [
                tf.Variable(tf.zeros_like(v), trainable=False)
                for v in self.inner_model.trainable_variables
            ]

        with tf.GradientTape() as tape:
            y_pred = self.inner_model(x, training=True)
            loss = self.compiled_loss(y, y_pred, sample_weight=sample_weight)
            # Scale loss for accumulation
            scaled_loss = loss / tf.cast(self.accumulation_steps, tf.float32)

        gradients = tape.gradient(scaled_loss, self.inner_model.trainable_variables)

        # Accumulate
        for accum, grad in zip(self._accum_gradients, gradients):
            if grad is not None:
                accum.assign_add(grad)

        self.step_count.assign_add(1)

        # Apply when accumulation is complete
        tf.cond(
            tf.equal(self.step_count % self.accumulation_steps, 0),
            lambda: self._apply_and_reset(),
            lambda: None,
        )

        # Update metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight=sample_weight)
        return {m.name: m.result() for m in self.metrics}

    def _apply_and_reset(self):
        self.optimizer.apply_gradients(
            zip(self._accum_gradients, self.inner_model.trainable_variables)
        )
        for accum in self._accum_gradients:
            accum.assign(tf.zeros_like(accum))


# ══════════════════════════════════════════════════════════════
# V25 — LAYER-WISE LEARNING RATE DECAY (LLRD)
# ══════════════════════════════════════════════════════════════

def build_llrd_optimizer(
    model: tf.keras.Model,
    base_lr: float,
    decay_factor: float = 0.75,
    clipnorm: float = 1.0,
) -> tf.keras.optimizers.Adam:
    """Build an Adam optimizer with layer-wise learning rate decay (LLRD).

    Deeper (earlier) layers get exponentially lower learning rates.
    This prevents catastrophic forgetting of pre-trained features while
    allowing the head layers to adapt aggressively.

    For TF2/Keras, we implement this using a single optimizer with per-variable
    learning rate scaling via optimizer.build() and custom LR multipliers,
    simplified as grouped parameter approach.

    In practice, we use a simple 3-group approach:
      - Head layers (custom dense/BN): base_lr
      - Top backbone layers (unfrozen): base_lr × decay_factor
      - Lower backbone layers (if unfrozen): base_lr × decay_factor^2

    Args:
        model: The full model (head + backbone)
        base_lr: Learning rate for head layers
        decay_factor: Multiplicative decay per depth group
        clipnorm: Gradient clipping norm

    Returns:
        Configured Adam optimizer
    """
    # For Keras 3.x / TF 2.16+, use the standard Adam with gradient clipping
    # LLRD is approximated by setting per-layer trainable status and
    # using different LR schedules during training phases.
    # The actual per-variable LR in TF2 requires tf.keras.optimizers.legacy.Adam
    # which is deprecated. Instead, we rely on progressive unfreezing which
    # achieves a similar effect: earlier unfrozen layers have already been
    # fine-tuned at lower LR in earlier phases.

    optimizer = tf.keras.optimizers.Adam(
        learning_rate=base_lr,
        clipnorm=clipnorm,
    )
    return optimizer


def build_cosine_restart_schedule(
    initial_lr: float,
    steps_per_epoch: int,
    restart_epochs: int = 5,
    t_mul: float = 1.5,
    m_mul: float = 0.9,
    alpha: float = 1e-7,
) -> tf.keras.optimizers.schedules.LearningRateSchedule:
    """Build a cosine annealing schedule with warm restarts (SGDR).

    Warm restarts allow the model to escape local minima in complex
    loss landscapes (like the spiral/irregular boundary).
    """
    first_decay_steps = steps_per_epoch * restart_epochs
    schedule = tf.keras.optimizers.schedules.CosineDecayRestarts(
        initial_learning_rate=initial_lr,
        first_decay_steps=first_decay_steps,
        t_mul=t_mul,
        m_mul=m_mul,
        alpha=alpha,
    )
    return schedule


# ══════════════════════════════════════════════════════════════
# V25 — SWA HELPER
# ══════════════════════════════════════════════════════════════

def run_swa(
    model: tf.keras.Model,
    train_ds: tf.data.Dataset,
    swa_epochs: int = 5,
    swa_lr_high: float = 1e-5,
    swa_lr_low: float = 5e-6,
) -> tf.keras.Model:
    """Apply Stochastic Weight Averaging to an already-trained model.

    SWA averages multiple checkpoints from a cyclical LR schedule,
    producing a model in a wider minimum with better generalization.
    Consistently adds +0.5-1.5% accuracy on fine-grained classification.

    After averaging, runs a BN update pass to recalculate batch
    normalization statistics for the averaged weights.
    """
    print('\n[SWA] Starting Stochastic Weight Averaging...')

    swa_weights = None
    n_snapshots = 0

    for epoch in range(swa_epochs):
        # Cyclical LR between swa_lr_high and swa_lr_low
        cycle_lr = float(swa_lr_low + (swa_lr_high - swa_lr_low) * (1 + np.cos(np.pi * epoch / swa_epochs)) / 2)

        # Recompile to safely update learning rate (bypasses Keras 3 issues with schedule objects)
        model.compile(
            optimizer=tf.keras.optimizers.Adam(learning_rate=cycle_lr, clipnorm=1.0),
            loss=model.loss,
        )

        model.fit(train_ds, epochs=1, verbose=0)
        print(f'  SWA epoch {epoch + 1}/{swa_epochs} | LR: {cycle_lr:.2e}')

        # Accumulate weights (running average)
        current_weights = [w.numpy() for w in model.weights]
        if swa_weights is None:
            swa_weights = [w.copy() for w in current_weights]
        else:
            for i in range(len(swa_weights)):
                swa_weights[i] = (swa_weights[i] * n_snapshots + current_weights[i]) / (n_snapshots + 1)
        n_snapshots += 1

    # Apply averaged weights
    for w, swa_w in zip(model.weights, swa_weights):
        w.assign(swa_w)

    # BN update pass (required after SWA weight averaging)
    print('  [SWA] Running BN statistics update...')
    bn_update_steps = 0
    for x_batch in train_ds:
        if isinstance(x_batch, tuple):
            x = x_batch[0]
        else:
            x = x_batch
        model(x, training=True)
        bn_update_steps += 1
        if bn_update_steps >= 50:
            break

    print(f'  [SWA] Complete. Averaged {n_snapshots} snapshots.')
    return model


# ============================================================
# START OF losses.py
# ============================================================


@tf.keras.utils.register_keras_serializable(package="Custom")
def rmse_metric(y_true, y_pred):
    """Root Mean Squared Error for the 37 regression targets."""
    mse = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)
    return tf.maximum(0.0, tf.sqrt(mse))

@tf.keras.utils.register_keras_serializable(package="Custom")
class RMSELoss(tf.keras.losses.Loss):
    """Direct RMSE loss function instead of standard MSE.

    Can be used directly to optimize against the Kaggle LB metric.
    Includes a small epsilon inside the square root for numerical stability.
    """
    def __init__(self, name="rmse_loss", **kwargs):
        super().__init__(name=name, **kwargs)

    def call(self, y_true, y_pred):
        # Calculate MSE across the 37 features
        mse = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)
        # Apply sqrt with epsilon to prevent infinite gradient at exactly 0.0 variance
        return tf.sqrt(tf.maximum(mse, tf.keras.backend.epsilon()))

    def get_config(self):
        return super().get_config()

@tf.keras.utils.register_keras_serializable(package="Custom")
class HierarchicalRMSELoss(tf.keras.losses.Loss):
    """Hierarchical RMSE loss that enforces Galaxy Zoo decision tree constraints.

    Ported from the legacy winning solution (benanne). This scales the errors of child
    nodes by the probability of their parent nodes, ensuring the model focuses on
    chemically/physically valid paths.
    """
    def __init__(self, name="hierarchical_rmse_loss", **kwargs):
        super().__init__(name=name, **kwargs)
        # Scaling sequence: (child_slice_start, child_slice_end, parent_index)
        self.scaling_sequence = [
            (3, 5, 1),    # Q2 scaled by Q1.2 (Features)
            (5, 13, 4),   # Q3, Q4, Q5 scaled by Q2.2 (No edge-on)
            (15, 18, 0),  # Q7 scaled by Q1.1 (Smooth)
            (18, 25, 13), # Q8 scaled by Q6.1 (Odd features)
            (25, 28, 3),  # Q9 scaled by Q2.1 (Edge-on)
            (28, 37, 7)   # Q10, Q11 scaled by Q4.1 (Spirals)
        ]

    def call(self, y_true, y_pred):
        # We apply the scaling to the predictions to match the hierarchy
        # However, the ground truth targets are already weighted in the dataset.
        # So we just calculate RMSE on the raw targets vs our hierarchical predictions.
        y_pred_h = self._apply_hierarchy(y_pred)

        mse = tf.reduce_mean(tf.square(y_true - y_pred_h), axis=-1)
        return tf.sqrt(tf.maximum(mse, tf.keras.backend.epsilon()))

    def _apply_hierarchy(self, y_pred):
        """Applies the hierarchical constraints to the prediction vector."""
        # Start with clipped predictions [0, 1]
        y_h = tf.clip_by_value(y_pred, 0.0, 1.0)

        for start, end, parent_idx in self.scaling_sequence:
            parent_prob = y_h[:, parent_idx : parent_idx + 1]
            # Rescale the child slice
            child_slice = y_h[:, start:end] * parent_prob

            # Reconstruct y_h with the updated slice
            parts = []
            if start > 0:
                parts.append(y_h[:, :start])
            parts.append(child_slice)
            if end < 37:
                parts.append(y_h[:, end:])
            y_h = tf.concat(parts, axis=1)

        return y_h

    def get_config(self):
        return super().get_config()


# ============================================================
# START OF model.py
# ============================================================




def _get_backbone(architecture: str, input_tensor: tf.Tensor) -> tf.keras.Model:
    """Instantiate a backbone model by architecture name with ImageNet weights."""
    arch_map = {
        'EfficientNetV2B0': tf.keras.applications.EfficientNetV2B0,
        'EfficientNetV2B1': tf.keras.applications.EfficientNetV2B1,
        'EfficientNetV2B2': tf.keras.applications.EfficientNetV2B2,
        'ConvNeXtTiny': tf.keras.applications.ConvNeXtTiny,
    }
    if architecture not in arch_map:
        raise ValueError(
            f'Unsupported architecture: {architecture}. '
            f'Available: {list(arch_map.keys())}'
        )
    return arch_map[architecture](
        include_top=False,
        weights='imagenet',
        input_tensor=input_tensor,
    )


@tf.keras.utils.register_keras_serializable(package="Custom")
class MultiViewLayer(tf.keras.layers.Layer):
    """Generates 8 orientations (4 rotations + 4 flips) of the input batch."""
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, inputs):
        # inputs: (Batch, H, W, 3)
        rot0 = inputs
        rot90 = tf.image.rot90(inputs, k=1)
        rot180 = tf.image.rot90(inputs, k=2)
        rot270 = tf.image.rot90(inputs, k=3)

        flip0 = tf.image.flip_left_right(rot0)
        flip90 = tf.image.flip_left_right(rot90)
        flip180 = tf.image.flip_left_right(rot180)
        flip270 = tf.image.flip_left_right(rot270)

        # Stack: (8, Batch, H, W, 3)
        views = tf.stack([rot0, rot90, rot180, rot270, flip0, flip90, flip180, flip270], axis=0)

        # Flatten: (8*Batch, H, W, 3)
        s = tf.shape(inputs)
        return tf.reshape(views, [8 * s[0], s[1], s[2], s[3]])

    def compute_output_shape(self, input_shape):
        batch = input_shape[0] * 8 if input_shape[0] is not None else None
        return (batch, input_shape[1], input_shape[2], input_shape[3])

@tf.keras.utils.register_keras_serializable(package="Custom")
class MultiViewAverage(tf.keras.layers.Layer):
    """Averages features or predictions across the 8 orientations."""
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, inputs):
        # inputs: (8*Batch, D)
        s = tf.shape(inputs)
        d = inputs.shape[-1]
        # Reshape to (8, Batch, D)
        x = tf.reshape(inputs, [8, s[0] // 8, d])
        return tf.reduce_mean(x, axis=0)

    def compute_output_shape(self, input_shape):
        batch = input_shape[0] // 8 if input_shape[0] is not None else None
        return (batch, input_shape[1])

def build_regression_model(
    architecture: str = 'EfficientNetV2B2',
    multi_view: bool = False,
) -> tuple[tf.keras.Model, tf.keras.Model]:
    """Build unified regression model: Predicts all 37 Galaxy Zoo probabilities.

    If multi_view is True, the model processes 8 rotations/flips and averages them.
    """
    inputs = tf.keras.Input(shape=(None, None, 3), name='image_input')

    x = inputs
    if multi_view:
        x = MultiViewLayer()(x)

    # Get backbone with ImageNet weights
    base_model = _get_backbone(architecture, x)

    # Process features
    x = tf.keras.layers.GlobalAveragePooling2D(name='gap')(base_model.output)

    if multi_view:
        # Average features across the 8 views before the dense head
        x = MultiViewAverage()(x)

    x = tf.keras.layers.BatchNormalization(name='bn1')(x)
    x = tf.keras.layers.Dense(512, name='dense1')(x)
    x = tf.keras.layers.BatchNormalization(name='bn2')(x)
    x = tf.keras.layers.Activation('gelu', name='gelu1')(x)
    x = tf.keras.layers.Dropout(0.4, name='dropout1')(x)

    outputs = tf.keras.layers.Dense(
        37, activation='sigmoid', dtype='float32', name='regression_output'
    )(x)

    model = tf.keras.Model(
        inputs=inputs, outputs=outputs,
        name=f'GalaxyNet_UnifiedRegression_{architecture}_MV' if multi_view else f'GalaxyNet_UnifiedRegression_{architecture}',
    )
    return model, base_model


def unfreeze_top_layers(base_model: tf.keras.Model, last_n: int) -> int:
    """Gradually unfreezes the last N layers of the base model for fine-tuning.

    All layers before the last N are frozen (not trainable).
    Returns the number of unfrozen layers (those with trainable weights).
    """
    base_model.trainable = True
    total_layers = len(base_model.layers)
    freeze_up_to = max(0, total_layers - last_n)
    for layer in base_model.layers[:freeze_up_to]:
        layer.trainable = False
    # Unfreeze everything after the boundary
    for layer in base_model.layers[freeze_up_to:]:
        layer.trainable = True
    # Count layers that are actually trainable and have weights
    unfrozen = sum(1 for l in base_model.layers[freeze_up_to:] if len(l.weights) > 0)
    return unfrozen


def freeze_base(base_model: tf.keras.Model) -> None:
    """Freeze all layers of the base model (for warmup phase)."""
    base_model.trainable = False


# ============================================================
# START OF dataset.py
# ============================================================







# ══════════════════════════════════════════════════════════════
# LABEL DETERMINATION (Regression - 37 Targets)
# ══════════════════════════════════════════════════════════════

def generate_labels_df(solutions_csv: Path, image_dir: Path) -> pd.DataFrame:
    """Generate 37-target DataFrame from Galaxy Zoo solutions CSV for Regression."""
    df = pd.read_csv(solutions_csv)

    # Automatically extract all 37 Class probability columns
    target_cols = [col for col in df.columns if col.startswith('Class')]
    if len(target_cols) != 37:
        print(f"WARNING: Expected 37 Class columns, found {len(target_cols)}")

    df['image_path'] = df['GalaxyID'].astype(str).apply(lambda gid: str(image_dir / f'{gid}.jpg'))

    # Check physical file existence to prune missing downloads
    df = df[df['image_path'].apply(lambda p: Path(p).exists())].copy()

    keep_cols = ['image_path'] + target_cols
    return df[keep_cols], target_cols


# ══════════════════════════════════════════════════════════════
# IMAGE LOADING & BASE PREPROCESSING
# ══════════════════════════════════════════════════════════════

def _smart_crop(image: tf.Tensor, ratio: float = 0.75) -> tf.Tensor:
    """Crops the image around its brightness centroid instead of the static center.

    Uses a Gaussian center prior to avoid latching onto background stars.
    """
    shape = tf.shape(image)
    h_int, w_int = shape[0], shape[1]
    h, w = tf.cast(h_int, tf.float32), tf.cast(w_int, tf.float32)

    # Calculate centroid using green channel (brightness approximation)
    img_green = image[..., 1]

    # Apply Gaussian center prior (sigma^2 = 5000 as in benanne solution)
    yy_grid, xx_grid = tf.meshgrid(tf.range(h_int), tf.range(w_int), indexing='ij')
    yy_grid = tf.cast(yy_grid, tf.float32)
    xx_grid = tf.cast(xx_grid, tf.float32)

    prior = tf.exp(-((yy_grid - h/2.0)**2 + (xx_grid - w/2.0)**2) / 5000.0)
    img_weighted = img_green * prior

    total_flux = tf.reduce_sum(img_weighted) + 1e-6

    # Weighted average coordinates
    cy = tf.reduce_sum(tf.reduce_sum(img_weighted, axis=1) * tf.cast(tf.range(h_int), tf.float32)) / total_flux
    cx = tf.reduce_sum(tf.reduce_sum(img_weighted, axis=0) * tf.cast(tf.range(w_int), tf.float32)) / total_flux

    # Clip centroid to keep the crop mostly within image bounds
    cy = tf.clip_by_value(cy, h * 0.1, h * 0.9)
    cx = tf.clip_by_value(cx, w * 0.1, w * 0.9)

    # Crop size
    ch = tf.cast(h * ratio, tf.int32)
    cw = tf.cast(w * ratio, tf.int32)

    offset_h = tf.cast(cy - tf.cast(ch, tf.float32) / 2.0, tf.int32)
    offset_w = tf.cast(cx - tf.cast(cw, tf.float32) / 2.0, tf.int32)

    # Final clamping to ensure valid crop
    offset_h = tf.clip_by_value(offset_h, 0, h_int - ch)
    offset_w = tf.clip_by_value(offset_w, 0, w_int - cw)

    return tf.image.crop_to_bounding_box(image, offset_h, offset_w, ch, cw)


def load_and_preprocess_image(path: tf.Tensor, label: tf.Tensor, image_size: int,
                               center_crop_ratio: float = 0.75):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.cast(img, tf.float32)
    img = _smart_crop(img, ratio=center_crop_ratio)
    img = tf.image.resize(img, [image_size, image_size])
    img = tf.clip_by_value(img, 0.0, 255.0)
    return img, label


# ══════════════════════════════════════════════════════════════
# AUGMENTATION
# ══════════════════════════════════════════════════════════════

def apply_cutout(image: tf.Tensor, n_holes: int = 2, max_size_ratio: float = 0.20) -> tf.Tensor:
    shape = tf.shape(image)
    h, w = shape[0], shape[1]
    img_mean = tf.reduce_mean(image)

    mask = tf.ones_like(image)
    for _ in range(n_holes):
        hole_size_h = tf.random.uniform([], minval=tf.cast(tf.cast(h, tf.float32) * 0.05, tf.int32),
                                         maxval=tf.maximum(tf.cast(tf.cast(h, tf.float32) * max_size_ratio, tf.int32), 2),
                                         dtype=tf.int32)
        hole_size_w = tf.random.uniform([], minval=tf.cast(tf.cast(w, tf.float32) * 0.05, tf.int32),
                                         maxval=tf.maximum(tf.cast(tf.cast(w, tf.float32) * max_size_ratio, tf.int32), 2),
                                         dtype=tf.int32)
        cy = tf.random.uniform([], minval=hole_size_h // 2, maxval=h - hole_size_h // 2, dtype=tf.int32)
        cx = tf.random.uniform([], minval=hole_size_w // 2, maxval=w - hole_size_w // 2, dtype=tf.int32)

        y1 = tf.maximum(cy - hole_size_h // 2, 0)
        y2 = tf.minimum(cy + hole_size_h // 2, h)
        x1 = tf.maximum(cx - hole_size_w // 2, 0)
        x2 = tf.minimum(cx + hole_size_w // 2, w)

        top_pad = y1
        bottom_pad = h - y2
        left_pad = x1
        right_pad = w - x2
        hole_h = y2 - y1
        hole_w = x2 - x1

        hole = tf.zeros([hole_h, hole_w, 3])
        hole = tf.pad(hole, [[top_pad, bottom_pad], [left_pad, right_pad], [0, 0]], constant_values=1.0)
        mask = mask * hole

    image = image * mask + img_mean * (1.0 - mask)
    return image


def apply_poisson_noise(image: tf.Tensor, scale: float = 25.0) -> tf.Tensor:
    img_norm = image / 255.0
    img_scaled = img_norm * scale
    noisy = tf.random.poisson(shape=[], lam=tf.maximum(img_scaled, 1e-6))
    noisy = noisy / scale * 255.0
    return tf.clip_by_value(noisy, 0.0, 255.0)


def apply_gaussian_blur(image: tf.Tensor, sigma: float = 1.0) -> tf.Tensor:
    kernel_size = tf.cast(tf.math.ceil(sigma * 3.0) * 2 + 1, tf.int32)
    kernel_size = tf.maximum(kernel_size, 3)
    half = tf.cast(kernel_size // 2, tf.float32)
    x = tf.range(-half, half + 1, dtype=tf.float32)
    kernel_1d = tf.exp(-x ** 2 / (2.0 * sigma ** 2))
    kernel_1d = kernel_1d / tf.reduce_sum(kernel_1d)
    kernel_2d = tf.tensordot(kernel_1d, kernel_1d, axes=0)
    kernel_2d = kernel_2d[:, :, tf.newaxis, tf.newaxis]
    kernel_2d = tf.tile(kernel_2d, [1, 1, 3, 1])

    image_4d = tf.expand_dims(image, 0)
    blurred = tf.nn.depthwise_conv2d(image_4d, kernel_2d, strides=[1, 1, 1, 1], padding='SAME')
    return tf.squeeze(blurred, 0)


def apply_continuous_rotation(image: tf.Tensor) -> tf.Tensor:
    if tfa is not None:
        angle = tf.random.uniform([], 0.0, 2.0 * math.pi)
        return tfa.image.rotate(image, angle, interpolation='BILINEAR')
    else:
        angle = tf.random.uniform([], 0.0, 2.0 * math.pi)
        cos_a = tf.cos(angle)
        sin_a = tf.sin(angle)
        h = tf.cast(tf.shape(image)[0], tf.float32)
        w = tf.cast(tf.shape(image)[1], tf.float32)
        cx, cy = w / 2.0, h / 2.0
        a2 = cx - cx * cos_a - cy * sin_a
        b2 = cy + cx * sin_a - cy * cos_a
        transform = [cos_a, sin_a, a2, -sin_a, cos_a, b2, 0.0, 0.0]
        transform = tf.cast(tf.stack(transform), tf.float32)
        transform = tf.reshape(transform, [1, 8])
        image_4d = tf.expand_dims(image, 0)
        rotated = tf.raw_ops.ImageProjectiveTransformV3(
            images=image_4d,
            transforms=transform,
            output_shape=tf.shape(image)[:2],
            fill_value=0.0,
            interpolation='BILINEAR',
            fill_mode='REFLECT',
        )
        return tf.squeeze(rotated, 0)


def augment_image(image: tf.Tensor, label: tf.Tensor):
    shape = tf.shape(image)
    orig_h, orig_w = shape[0], shape[1]

    image = apply_continuous_rotation(image)
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)

    if tf.random.uniform([]) < 0.3:
        image = apply_poisson_noise(image, scale=25.0)

    if tf.random.uniform([]) < 0.2:
        sigma = tf.random.uniform([], 0.5, 2.0)
        image = apply_gaussian_blur(image, sigma)

    if tf.random.uniform([]) > 0.5:
        image = tf.image.random_brightness(image, max_delta=0.15 * 255.0)
        image = tf.image.random_contrast(image, lower=0.85, upper=1.15)

    crop_h = tf.cast(tf.cast(orig_h, tf.float32) * 0.9, tf.int32)
    crop_w = tf.cast(tf.cast(orig_w, tf.float32) * 0.9, tf.int32)
    image = tf.image.random_crop(image, [crop_h, crop_w, 3])
    image = tf.image.resize(image, [orig_h, orig_w])

    if tf.random.uniform([]) > 0.7:
        image = apply_cutout(image, n_holes=1, max_size_ratio=0.15)

    image = tf.clip_by_value(image, 0.0, 255.0)
    return image, label


# ══════════════════════════════════════════════════════════════
# DATASET BUILDERS
# ══════════════════════════════════════════════════════════════

def build_dataset(
    image_paths: np.ndarray,
    labels: np.ndarray,
    image_size: int,
    batch_size: int,
    center_crop_ratio: float = 0.75,
    augment: bool = False,
    shuffle: bool = False,
    cache: bool = False,
) -> tf.data.Dataset:
    """Build a tf.data.Dataset mapping paths and 37-node target vectors."""
    ds = tf.data.Dataset.from_tensor_slices((image_paths, labels))
    ds = ds.map(
        lambda p, y: load_and_preprocess_image(p, y, image_size, center_crop_ratio),
        num_parallel_calls=tf.data.AUTOTUNE,
    )

    if shuffle:
        ds = ds.shuffle(buffer_size=min(len(image_paths), 10000), reshuffle_each_iteration=True)

    if augment:
        ds = ds.map(lambda i, l: augment_image(i, l), num_parallel_calls=tf.data.AUTOTUNE)

    if cache:
        ds = ds.cache()

    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds


# ══════════════════════════════════════════════════════════════
# SPLITTING & ORCHESTRATION
# ══════════════════════════════════════════════════════════════

def build_datasets(labels_df: pd.DataFrame, config: Config):
    """Split data randomly for regression."""
    train_df, temp_df = train_test_split(
        labels_df,
        test_size=config.val_split + config.test_split,
        random_state=config.seed,
    )
    test_ratio_of_temp = config.test_split / (config.val_split + config.test_split)
    val_df, test_df = train_test_split(
        temp_df,
        test_size=test_ratio_of_temp,
        random_state=config.seed,
    )

    train_df = train_df.reset_index(drop=True)
    val_df = val_df.reset_index(drop=True)
    test_df = test_df.reset_index(drop=True)

    split_info = {
        'train_size': len(train_df),
        'val_size': len(val_df),
        'test_size': len(test_df),
        'total_labeled_images': len(labels_df),
    }

    return split_info, (train_df, val_df, test_df)


# ============================================================
# START OF evaluate.py
# ============================================================



from tqdm import tqdm



def calculate_rmse(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """Calculate the global Root Mean Squared Error over all targets."""
    mse = np.mean(np.square(y_true - y_pred))
    return np.sqrt(mse)


def predict_tta(model: tf.keras.Model, test_paths: np.ndarray, config: Config) -> np.ndarray:
    """Run Test-Time Augmentation (TTA) and return averaged predictions."""
    print(f"\n[Evaluation] Running TTA ({config.tta_n_augments} passes)...")

    # Dummy labels for the dataset builder
    dummy_labels = np.zeros((len(test_paths), 37), dtype=np.float32)

    tta_preds = []

    # Pass 1: Original (unaugmented) center crop
    ds_base = build_dataset(
        test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
    )
    base_preds = model.predict(ds_base, verbose=1)
    tta_preds.append(base_preds)

    # Passes 2 to N: Augmented crops/rotations
    for i in range(config.tta_n_augments - 1):
        ds_aug = build_dataset(
            test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
            center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=False,
        )
        preds = model.predict(ds_aug, verbose=0)
        tta_preds.append(preds)
        print(f"  TTA pass {i+2}/{config.tta_n_augments} completed.")

    return np.mean(tta_preds, axis=0)


def evaluate_regression(config: Config, test_df: pd.DataFrame, target_cols: list[str]):
    """Evaluate the single unified regression model using RMSE."""
    output_dir = config.output_dir
    model_path = output_dir / 'unified_best.keras'

    if not model_path.exists():
        print(f"Error: Unified model not found at {model_path}")
        return

    print('\n' + '=' * 60)
    print('EVALUATION: REGRESSION RMSE')
    print('=' * 60)

    # Load model
    print("Loading unified model...")
    custom_objects = {
        'RMSELoss': RMSELoss,
        'HierarchicalRMSELoss': HierarchicalRMSELoss,
        'rmse_metric': rmse_metric,
        'MultiViewLayer': MultiViewLayer,
        'MultiViewAverage': MultiViewAverage,
    }
    model = tf.keras.models.load_model(model_path, custom_objects=custom_objects)

    test_paths = test_df['image_path'].values
    y_true = test_df[target_cols].values.astype(np.float32)

    # Standard Prediction (No TTA)
    dummy_labels = np.zeros_like(y_true)
    ds_test = build_dataset(
        test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
    )

    print("\nRunning standard evaluation (1-pass)...")
    y_pred_std = model.predict(ds_test, verbose=1)
    rmse_std = calculate_rmse(y_true, y_pred_std)

    # TTA Prediction
    y_pred_tta = predict_tta(model, test_paths, config)
    rmse_tta = calculate_rmse(y_true, y_pred_tta)

    # Report
    print('\n' + '-' * 40)
    print("TEST METRICS (Kaggle Leaderboard Objective)")
    print('-' * 40)
    print(f"  RMSE (Single Pass): {rmse_std:.5f}")
    print(f"  RMSE (TTA {config.tta_n_augments}x):     {rmse_tta:.5f}")
    print('-' * 40)

    # Save results
    results = {
        'test_size': len(test_df),
        'rmse_standard': float(rmse_std),
        'rmse_tta': float(rmse_tta),
    }

    with open(output_dir / 'evaluation_results.json', 'w') as f:
        json.dump(results, f, indent=2)

    print(f"\nEvaluation complete. Results saved to {output_dir / 'evaluation_results.json'}")


# ============================================================
# START OF train.py
# ============================================================






class ConciseLogging(tf.keras.callbacks.Callback):
    """Minimal logging to prevent log flooding during long regression runs."""
    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}
        lr = self.model.optimizer.learning_rate
        if isinstance(lr, tf.keras.optimizers.schedules.LearningRateSchedule):
            lr_val = float(lr(self.model.optimizer.iterations))
        else:
            # Handle standard variables or distributed MirroredVariables
            lr_val = float(tf.convert_to_tensor(lr))

        print(f"Epoch {epoch+1:02d} | Loss: {logs.get('loss', 0):.5f} | "
              f"Val RMSE: {logs.get('val_rmse_metric', 0):.5f} | LR: {lr_val:.2e}")


def train_unified_regression(config: Config, solutions_csv: Path, image_dir: Path):
    """Unified progressive resizing training loop for 37-node regression on TPU."""
    output_dir = config.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Strategy Initialization ──
    strategy = get_strategy()

    # ── Dataset Preparation ──
    df, target_cols = generate_labels_df(solutions_csv, image_dir)
    split_info, (train_df, val_df, test_df) = build_datasets(df, config)

    train_paths = train_df['image_path'].values[:100]
    train_labels = train_df[target_cols].values[:100].astype(np.float32)
    val_paths = val_df['image_path'].values[:20]
    val_labels = val_df[target_cols].values[:20].astype(np.float32)

    # Scale batch sizes by number of TPU replicas
    bs1 = config.get_scaled_batch_size(config.batch_size_phase1, strategy)
    bs2 = config.get_scaled_batch_size(config.batch_size_phase2, strategy)
    bs3 = config.get_scaled_batch_size(config.batch_size_phase3, strategy)

    print(f"Global Batch Sizes (all cores): P1={bs1}, P2={bs2}, P3={bs3}")

    # ── Model & Strategy Scope ──
    with strategy.scope():
        model, base_model = build_regression_model(config.architecture, multi_view=config.multi_view)
        loss_fn = HierarchicalRMSELoss()

    # ── Phase 1: Warmup (Fixed layers, 128px) ──
    print('\n[Phase 1] Warmup (Frozen Backbone, 128px)')
    freeze_base(base_model)

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase1, bs1,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase1, bs1,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
    )

    with strategy.scope():
        model.compile(
            optimizer=tf.keras.optimizers.Adam(config.warmup_lr),
            loss=loss_fn, metrics=[rmse_metric],
        )
        train_model = model

    train_model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.warmup_epochs,
        callbacks=[ConciseLogging()],
        verbose=0,
    )

    # ── Phase 2: Mid-tune (Partial unfreeze, 192px) ──
    print(f'\n[Phase 2] Mid-tune (Unfreeze {config.unfreeze_phase2} layers, 192px)')
    unfreeze_top_layers(base_model, config.unfreeze_phase2)

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase2, bs2,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase2, bs2,
        center_crop_ratio=config.center_crop_ratio,
    )

    with strategy.scope():
        steps_per_epoch = len(train_paths) // bs2
        lr_schedule = build_cosine_restart_schedule(
            config.midtune_lr, steps_per_epoch, restart_epochs=5
        )
        model.compile(
            optimizer=tf.keras.optimizers.Adam(lr_schedule, clipnorm=1.0),
            loss=loss_fn, metrics=[rmse_metric],
        )
        train_model = model

    train_model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.midtune_epochs,
        callbacks=[ConciseLogging()],
        verbose=0,
    )

    # ── Phase 3: Fine-tune (More unfreeze, 384px) ──
    print(f'\n[Phase 3] Fine-tune (Unfreeze {config.unfreeze_phase3} layers, {config.image_size_phase3}px)')
    unfreeze_top_layers(base_model, config.unfreeze_phase3)

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase3, bs3,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase3, bs3,
        center_crop_ratio=config.center_crop_ratio,
    )

    with strategy.scope():
        steps_per_epoch = len(train_paths) // bs3
        lr_schedule_p3 = build_cosine_restart_schedule(
            config.finetune_lr, steps_per_epoch, restart_epochs=5
        )
        model.compile(
            optimizer=tf.keras.optimizers.Adam(lr_schedule_p3, clipnorm=1.0),
            loss=loss_fn, metrics=[rmse_metric],
        )
        train_model = model

    train_model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.finetune_epochs,
        callbacks=[
            tf.keras.callbacks.ModelCheckpoint(
                str(output_dir / 'unified_best.keras'),
                monitor='val_rmse_metric', save_best_only=True, mode='min',
            ),
            ConciseLogging(),
        ],
        verbose=0,
    )

    # ── SWA ──
    print('\n[SWA Phase]')
    train_ds_swa = build_dataset(
        train_paths, train_labels, config.image_size_phase3, bs3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=True,
    )
    model = run_swa(model, train_ds_swa, config.swa_epochs, config.swa_lr_high, config.swa_lr_low)
    model.save(str(output_dir / 'unified_best.keras'))

    # Save details
    save_json(output_dir / 'split_info.json', split_info)

    # Cleanup
    tf.keras.backend.clear_session()
    gc.collect()

    return test_df, target_cols


def main():
    t0 = time.time()
    config = Config()

    setup_environment(config)

    if is_kaggle_runtime():
        solutions_csv, image_dir = setup_kaggle_environment(config)
    else:
        solutions_csv = Path("galaxy_raw/training_solutions_rev1.csv")
        image_dir = Path("galaxy_raw/training_images/images_training_rev1")

    # Run pipeline
    test_df, target_cols = train_unified_regression(config, solutions_csv, image_dir)

    print(f"\nTraining pipeline completed in {(time.time() - t0) / 60:.1f} minutes.")

    # Run evaluation
    evaluate_regression(config, test_df, target_cols)


if __name__ == '__main__':
    main()
