# AUTO-GENERATED KAGGLE BUNDLE — GalaxyNet V25 Cascade Pipeline
# This file merges modular components for Kaggle compatibility.
# Generated by scripts/consolidate.py

from __future__ import annotations

import argparse
import datetime
import gc
import json
import math
import multiprocessing
import os
import pickle
import random
import subprocess
import sys
import time
import zipfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Tuple

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import (
    brier_score_loss,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split

try:
    import tensorflow_addons as tfa
except Exception:
    tfa = None

try:
    import xgboost as xgb
except ImportError:
    xgb = None

# ============================================================
# START OF config.py
# ============================================================



@dataclass
class Config:
    # ── Paths ──────────────────────────────────────────────────
    kaggle_input_dir: Path = Path('/kaggle/input/galaxy-zoo-the-galaxy-challenge')
    kaggle_temp_dir: Path = Path('/kaggle/temp')
    output_dir: Path = Path('outputs')

    # ── Image resolution curriculum ────────────────────────────
    image_size_phase1: int = 424
    image_size_phase2: int = 424
    image_size_phase3: int = 424
    center_crop_ratio: float = 1.0

    # ── Batch sizes (BASE per device - Optimized for T4 16GB) ──
    batch_size_phase1: int = 16
    batch_size_phase2: int = 16
    batch_size_phase3: int = 16
    grad_accumulation_steps: int = 1  # Disabled for MirroredStrategy stability

    # ── Data split ─────────────────────────────────────────────
    seed: int = 42
    val_split: float = 0.10
    test_split: float = 0.00
    legacy_ordered_split: bool = True

    # ── Model Architecture ─────────────────────────────────────
    architecture: str = 'BenanneNetTF'
    multi_view: bool = False

    # ── Training Schedule ──────────────────────────────────────
    warmup_epochs: int = 8
    midtune_epochs: int = 10
    finetune_epochs: int = 12

    warmup_lr: float = 4e-2
    midtune_lr: float = 4e-3
    finetune_lr: float = 4e-4

    unfreeze_phase2: int = 50
    unfreeze_phase3: int = 100

    # ── Augmentation ───────────────────────────────────────────
    mixup_alpha: float = 0.4
    mixup_prob: float = 0.5
    cutout_n_holes: int = 2
    cutout_max_size_ratio: float = 0.20

    # ── Astronomy-Specific Augmentations (V26) ─────────────────
    augment_poisson_scale: float = 25.0
    augment_poisson_prob: float = 0.3
    augment_blur_prob: float = 0.2
    augment_blur_sigma_range: Tuple[float, float] = (0.5, 2.0)

    # ── SWA ────────────────────────────────────────────────────
    swa_epochs: int = 0
    swa_lr_high: float = 5e-6
    swa_lr_low: float = 1e-6

    # ── TTA ────────────────────────────────────────────────────
    tta_n_augments: int = 60
    submission_filename: str = 'submission.csv.gz'

    # ── Runtime ────────────────────────────────────────────────
    enable_mixed_precision: bool = True

    def get_scaled_batch_size(self, base_size: int, strategy: tf.distribute.Strategy) -> int:
        return base_size * strategy.num_replicas_in_sync


# ============================================================
# START OF utils.py
# ============================================================






def set_global_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)


def get_strategy() -> tf.distribute.Strategy:
    """Detect and initialize the appropriate distribution strategy."""
    try:
        # Standard TPU detection
        tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
        tf.config.experimental_connect_to_cluster(tpu)
        tf.tpu.experimental.initialize_tpu_system(tpu)
        strategy = tf.distribute.TPUStrategy(tpu)
        print(f"Running on TPU (Standard): {tpu.cluster_spec().as_dict()}")
        return strategy
    except (ValueError, RuntimeError, tf.errors.NotFoundError):
        try:
            # Fallback for some Kaggle environments (TPU v5 or newer)
            tpu = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='local')
            tf.config.experimental_connect_to_cluster(tpu)
            tf.tpu.experimental.initialize_tpu_system(tpu)
            strategy = tf.distribute.TPUStrategy(tpu)
            print("Running on TPU (Local Resolver)")
            return strategy
        except (ValueError, RuntimeError, tf.errors.NotFoundError):
            gpus = tf.config.list_physical_devices('GPU')
            if gpus:
                print(f"Running on GPU: {len(gpus)} device(s)")
                return tf.distribute.MirroredStrategy()
            else:
                print("Running on CPU")
                return tf.distribute.get_strategy()


def setup_environment(config: Config) -> None:
    set_global_seed(config.seed)

    if config.enable_mixed_precision:
        # Determine policy based on ACTUAL hardware presence
        # TPU v3/v5 prefers bfloat16, GPU prefers float16
        is_tpu = any(os.environ.get(k) for k in ['TPU_NAME', 'KAGGLE_TPU_ADDR', 'COLAB_TPU_ADDR'])

        policy = 'mixed_bfloat16' if is_tpu else 'mixed_float16'
        tf.keras.mixed_precision.set_global_policy(policy)

    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)

    # Final check for visibility
    if not any(os.environ.get(k) for k in ['TPU_NAME', 'KAGGLE_TPU_ADDR']) and not gpus:
        print('Warning: No Hardware Accelerator (GPU/TPU) detected — running on CPU')


def find_kaggle_file(root: Path, name: str) -> Path:
    matches = list(root.rglob(name))
    if not matches:
        raise FileNotFoundError(f'Could not find {name} under {root}')
    return matches[0]


def _extract_zip_if_needed(zip_path: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(output_dir)


def _resolve_competition_environment(search_roots: list[Path], temp_dir: Path) -> Tuple[Path, Path, Path, Path]:
    def find_robustly(name: str):
        for root in search_roots:
            if not root.exists():
                continue
            try:
                return find_kaggle_file(root, name)
            except FileNotFoundError:
                continue
        raise FileNotFoundError(f"Could not find {name} in any of {search_roots}")

    # Try to find CSV directly first (if already unzipped)
    try:
        csv_path = find_robustly('training_solutions_rev1.csv')
    except FileNotFoundError:
        # If not, find and extract zip
        train_csv_zip = find_robustly('training_solutions_rev1.zip')
        _extract_zip_if_needed(train_csv_zip, temp_dir)
        csv_path = find_kaggle_file(temp_dir, 'training_solutions_rev1.csv')

    # Try to find training image dir directly
    try:
        image_dir_candidate = find_robustly('images_training_rev1')
        if not image_dir_candidate.is_dir():
            raise FileNotFoundError
        train_check = list(Path(image_dir_candidate).glob('*.jpg'))
        if len(train_check) < 10:
            raise FileNotFoundError
        train_image_dir = image_dir_candidate
    except FileNotFoundError:
        image_zip = find_robustly('images_training_rev1.zip')
        _extract_zip_if_needed(image_zip, temp_dir)
        train_image_dir = find_kaggle_file(temp_dir, 'images_training_rev1')

    # Try to find test image dir directly
    try:
        test_dir_candidate = find_robustly('images_test_rev1')
        if not test_dir_candidate.is_dir():
            raise FileNotFoundError
        test_check = list(Path(test_dir_candidate).glob('*.jpg'))
        if len(test_check) < 10:
            raise FileNotFoundError
        test_image_dir = test_dir_candidate
    except FileNotFoundError:
        test_zip = find_robustly('images_test_rev1.zip')
        _extract_zip_if_needed(test_zip, temp_dir)
        test_image_dir = find_kaggle_file(temp_dir, 'images_test_rev1')

    try:
        submission_template_path = find_robustly('all_zeros_benchmark.zip')
    except FileNotFoundError:
        submission_template_path = find_robustly('all_zeros_benchmark.csv')

    return (
        Path(csv_path),
        Path(train_image_dir),
        Path(test_image_dir),
        Path(submission_template_path),
    )


def setup_kaggle_environment(config: Config) -> Tuple[Path, Path, Path, Path]:
    search_roots = [config.kaggle_input_dir, Path('/kaggle/input')]
    return _resolve_competition_environment(search_roots, config.kaggle_temp_dir)


def setup_local_environment(config: Config) -> Tuple[Path, Path, Path, Path]:
    local_root = Path('galaxy_raw')
    search_roots = [local_root]
    return _resolve_competition_environment(search_roots, local_root)


def save_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2, default=str)


def is_kaggle_runtime() -> bool:
    return os.environ.get('KAGGLE_KERNEL_RUN_TYPE') is not None


# ══════════════════════════════════════════════════════════════
# V25 — GRADIENT ACCUMULATION HELPER
# ══════════════════════════════════════════════════════════════

@tf.keras.utils.register_keras_serializable(package="Custom")
class GradientAccumulationModel(tf.keras.Model):
    """Wrapper model that accumulates gradients over N mini-batches
    before applying an optimizer step. This allows effective large
    batch sizes when VRAM is limited (e.g., batch_size=16 × accum=2 = 32 effective).

    Usage:
        ga_model = GradientAccumulationModel(base_model, accumulation_steps=2)
        ga_model.compile(optimizer=..., loss=..., metrics=...)
        ga_model.fit(train_ds, ...)
    """

    def __init__(self, inner_model: tf.keras.Model, accumulation_steps: int = 2, **kwargs):
        super().__init__(**kwargs)
        self.inner_model = inner_model
        self.accumulation_steps = accumulation_steps
        self.step_count = tf.Variable(0, trainable=False, dtype=tf.int32)
        self._accum_gradients = None

    def get_config(self):
        config = super().get_config()
        config.update({
            "inner_model": self.inner_model,
            "accumulation_steps": self.accumulation_steps,
        })
        return config

    def call(self, inputs, training=False):
        return self.inner_model(inputs, training=training)

    @property
    def trainable_variables(self):
        return self.inner_model.trainable_variables

    def train_step(self, data):
        if len(data) == 3:
            x, y, sample_weight = data
        else:
            x, y = data
            sample_weight = None

        # Initialize gradient accumulators on first call
        if self._accum_gradients is None:
            self._accum_gradients = [
                tf.Variable(tf.zeros_like(v), trainable=False)
                for v in self.inner_model.trainable_variables
            ]

        with tf.GradientTape() as tape:
            y_pred = self.inner_model(x, training=True)
            loss = self.compiled_loss(y, y_pred, sample_weight=sample_weight)
            # Scale loss for accumulation
            scaled_loss = loss / tf.cast(self.accumulation_steps, tf.float32)

        gradients = tape.gradient(scaled_loss, self.inner_model.trainable_variables)

        # Accumulate
        for accum, grad in zip(self._accum_gradients, gradients):
            if grad is not None:
                accum.assign_add(grad)

        self.step_count.assign_add(1)

        # Apply when accumulation is complete
        tf.cond(
            tf.equal(self.step_count % self.accumulation_steps, 0),
            lambda: self._apply_and_reset(),
            lambda: None,
        )

        # Update metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight=sample_weight)
        return {m.name: m.result() for m in self.metrics}

    def _apply_and_reset(self):
        self.optimizer.apply_gradients(
            zip(self._accum_gradients, self.inner_model.trainable_variables)
        )
        for accum in self._accum_gradients:
            accum.assign(tf.zeros_like(accum))


# ══════════════════════════════════════════════════════════════
# V25 — LAYER-WISE LEARNING RATE DECAY (LLRD)
# ══════════════════════════════════════════════════════════════

def build_llrd_optimizer(
    model: tf.keras.Model,
    base_lr: float,
    decay_factor: float = 0.75,
    clipnorm: float = 1.0,
) -> tf.keras.optimizers.Adam:
    """Build an Adam optimizer with layer-wise learning rate decay (LLRD).

    Deeper (earlier) layers get exponentially lower learning rates.
    This prevents catastrophic forgetting of pre-trained features while
    allowing the head layers to adapt aggressively.

    For TF2/Keras, we implement this using a single optimizer with per-variable
    learning rate scaling via optimizer.build() and custom LR multipliers,
    simplified as grouped parameter approach.

    In practice, we use a simple 3-group approach:
      - Head layers (custom dense/BN): base_lr
      - Top backbone layers (unfrozen): base_lr × decay_factor
      - Lower backbone layers (if unfrozen): base_lr × decay_factor^2

    Args:
        model: The full model (head + backbone)
        base_lr: Learning rate for head layers
        decay_factor: Multiplicative decay per depth group
        clipnorm: Gradient clipping norm

    Returns:
        Configured Adam optimizer
    """
    # For Keras 3.x / TF 2.16+, use the standard Adam with gradient clipping
    # LLRD is approximated by setting per-layer trainable status and
    # using different LR schedules during training phases.
    # The actual per-variable LR in TF2 requires tf.keras.optimizers.legacy.Adam
    # which is deprecated. Instead, we rely on progressive unfreezing which
    # achieves a similar effect: earlier unfrozen layers have already been
    # fine-tuned at lower LR in earlier phases.

    optimizer = tf.keras.optimizers.Adam(
        learning_rate=base_lr,
        clipnorm=clipnorm,
    )
    return optimizer


def build_cosine_restart_schedule(
    initial_lr: float,
    steps_per_epoch: int,
    restart_epochs: int = 5,
    t_mul: float = 1.5,
    m_mul: float = 0.9,
    alpha: float = 1e-7,
) -> tf.keras.optimizers.schedules.LearningRateSchedule:
    """Build a cosine annealing schedule with warm restarts (SGDR).

    Warm restarts allow the model to escape local minima in complex
    loss landscapes (like the spiral/irregular boundary).
    """
    first_decay_steps = steps_per_epoch * restart_epochs
    schedule = tf.keras.optimizers.schedules.CosineDecayRestarts(
        initial_learning_rate=initial_lr,
        first_decay_steps=first_decay_steps,
        t_mul=t_mul,
        m_mul=m_mul,
        alpha=alpha,
    )
    return schedule


# ══════════════════════════════════════════════════════════════
# V25 — SWA HELPER
# ══════════════════════════════════════════════════════════════

def run_swa(
    model: tf.keras.Model,
    train_ds: tf.data.Dataset,
    swa_epochs: int = 5,
    swa_lr_high: float = 1e-5,
    swa_lr_low: float = 5e-6,
) -> tf.keras.Model:
    """Apply Stochastic Weight Averaging to an already-trained model.

    SWA averages multiple checkpoints from a cyclical LR schedule,
    producing a model in a wider minimum with better generalization.
    Consistently adds +0.5-1.5% accuracy on fine-grained classification.

    After averaging, runs a BN update pass to recalculate batch
    normalization statistics for the averaged weights.
    """
    print('\n[SWA] Starting Stochastic Weight Averaging...')

    swa_weights = None
    n_snapshots = 0

    for epoch in range(swa_epochs):
        # Cyclical LR between swa_lr_high and swa_lr_low
        cycle_lr = float(swa_lr_low + (swa_lr_high - swa_lr_low) * (1 + np.cos(np.pi * epoch / swa_epochs)) / 2)

        # Recompile to safely update learning rate (bypasses Keras 3 issues with schedule objects)
        model.compile(
            optimizer=tf.keras.optimizers.Adam(learning_rate=cycle_lr, clipnorm=1.0),
            loss=model.loss,
        )

        model.fit(train_ds, epochs=1, verbose=0)
        print(f'  SWA epoch {epoch + 1}/{swa_epochs} | LR: {cycle_lr:.2e}')

        # Accumulate weights (running average)
        current_weights = [w.numpy() for w in model.weights]
        if swa_weights is None:
            swa_weights = [w.copy() for w in current_weights]
        else:
            for i in range(len(swa_weights)):
                swa_weights[i] = (swa_weights[i] * n_snapshots + current_weights[i]) / (n_snapshots + 1)
        n_snapshots += 1

    # Apply averaged weights
    for w, swa_w in zip(model.weights, swa_weights):
        w.assign(swa_w)

    # BN update pass (required after SWA weight averaging)
    print('  [SWA] Running BN statistics update...')
    bn_update_steps = 0
    for x_batch in train_ds:
        if isinstance(x_batch, tuple):
            x = x_batch[0]
        else:
            x = x_batch
        model(x, training=True)
        bn_update_steps += 1
        if bn_update_steps >= 50:
            break

    print(f'  [SWA] Complete. Averaged {n_snapshots} snapshots.')
    return model


# ============================================================
# START OF losses.py
# ============================================================


@tf.keras.utils.register_keras_serializable(package="Custom")
def rmse_metric(y_true, y_pred):
    """Root Mean Squared Error for the 37 regression targets."""
    mse = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)
    return tf.maximum(0.0, tf.sqrt(mse))

@tf.keras.utils.register_keras_serializable(package="Custom")
class RMSELoss(tf.keras.losses.Loss):
    """Direct RMSE loss function instead of standard MSE.

    Can be used directly to optimize against the Kaggle LB metric.
    Includes a small epsilon inside the square root for numerical stability.
    """
    def __init__(self, name="rmse_loss", **kwargs):
        super().__init__(name=name, **kwargs)

    def call(self, y_true, y_pred):
        # Calculate MSE across the 37 features
        mse = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)
        # Apply sqrt with epsilon to prevent infinite gradient at exactly 0.0 variance
        return tf.sqrt(tf.maximum(mse, tf.keras.backend.epsilon()))

    def get_config(self):
        return super().get_config()

@tf.keras.utils.register_keras_serializable(package="Custom")
class HierarchicalRMSELoss(tf.keras.losses.Loss):
    """Hierarchical RMSE loss that enforces Galaxy Zoo decision tree constraints.

    Ported from the legacy winning solution (benanne). This scales the errors of child
    nodes by the probability of their parent nodes, ensuring the model focuses on
    chemically/physically valid paths.
    """
    def __init__(self, name="hierarchical_rmse_loss", **kwargs):
        super().__init__(name=name, **kwargs)
        # Scaling sequence: (child_slice_start, child_slice_end, parent_index)
        self.scaling_sequence = [
            (3, 5, 1),    # Q2 scaled by Q1.2 (Features)
            (5, 13, 4),   # Q3, Q4, Q5 scaled by Q2.2 (No edge-on)
            (15, 18, 0),  # Q7 scaled by Q1.1 (Smooth)
            (18, 25, 13), # Q8 scaled by Q6.1 (Odd features)
            (25, 28, 3),  # Q9 scaled by Q2.1 (Edge-on)
            (28, 37, 7)   # Q10, Q11 scaled by Q4.1 (Spirals)
        ]

    def call(self, y_true, y_pred):
        # We apply the scaling to the predictions to match the hierarchy
        # However, the ground truth targets are already weighted in the dataset.
        # So we just calculate RMSE on the raw targets vs our hierarchical predictions.
        y_pred_h = self._apply_hierarchy(y_pred)

        mse = tf.reduce_mean(tf.square(y_true - y_pred_h), axis=-1)
        return tf.sqrt(tf.maximum(mse, tf.keras.backend.epsilon()))

    def _apply_hierarchy(self, y_pred):
        """Applies the hierarchical constraints to the prediction vector."""
        # Start with clipped predictions [0, 1]
        y_h = tf.clip_by_value(y_pred, 0.0, 1.0)

        for start, end, parent_idx in self.scaling_sequence:
            parent_prob = y_h[:, parent_idx : parent_idx + 1]
            # Rescale the child slice
            child_slice = y_h[:, start:end] * parent_prob

            # Reconstruct y_h with the updated slice
            parts = []
            if start > 0:
                parts.append(y_h[:, :start])
            parts.append(child_slice)
            if end < 37:
                parts.append(y_h[:, end:])
            y_h = tf.concat(parts, axis=1)

        return y_h

    def get_config(self):
        return super().get_config()


# ============================================================
# START OF model.py
# ============================================================




QUESTION_SLICES = (
    (0, 3),
    (3, 5),
    (5, 7),
    (7, 9),
    (9, 13),
    (13, 15),
    (15, 18),
    (18, 25),
    (25, 28),
    (28, 31),
    (31, 37),
)

SCALING_SEQUENCE = (
    (3, 5, 1),
    (5, 13, 4),
    (15, 18, 0),
    (18, 25, 13),
    (25, 28, 3),
    (28, 37, 7),
)


def _rotate_batch(images: tf.Tensor, angle_degrees: float) -> tf.Tensor:
    angle = tf.constant(angle_degrees * 3.141592653589793 / 180.0, dtype=tf.float32)
    cos_a = tf.cos(angle)
    sin_a = tf.sin(angle)
    image_shape = tf.shape(images)
    batch = image_shape[0]
    h = tf.cast(image_shape[1], tf.float32)
    w = tf.cast(image_shape[2], tf.float32)
    cx = (w - 1.0) / 2.0
    cy = (h - 1.0) / 2.0

    a0 = cos_a
    a1 = sin_a
    a2 = cx - a0 * cx - a1 * cy
    b0 = -sin_a
    b1 = cos_a
    b2 = cy - b0 * cx - b1 * cy
    transform = tf.stack([a0, a1, a2, b0, b1, b2, 0.0, 0.0])
    transforms = tf.tile(tf.reshape(transform, [1, 8]), [batch, 1])

    return tf.raw_ops.ImageProjectiveTransformV3(
        images=images,
        transforms=transforms,
        output_shape=image_shape[1:3],
        fill_value=0.0,
        interpolation='BILINEAR',
        fill_mode='REFLECT',
    )


def _get_backbone(architecture: str, input_tensor: tf.Tensor) -> tf.keras.Model:
    """Instantiate a backbone model by architecture name with ImageNet weights."""
    arch_map = {
        'EfficientNetV2B0': tf.keras.applications.EfficientNetV2B0,
        'EfficientNetV2B1': tf.keras.applications.EfficientNetV2B1,
        'EfficientNetV2B2': tf.keras.applications.EfficientNetV2B2,
        'ConvNeXtTiny': tf.keras.applications.ConvNeXtTiny,
    }
    if architecture not in arch_map:
        raise ValueError(
            f'Unsupported architecture: {architecture}. '
            f'Available: {list(arch_map.keys())}'
        )
    return arch_map[architecture](
        include_top=False,
        weights='imagenet',
        input_tensor=input_tensor,
    )


@tf.keras.utils.register_keras_serializable(package="Custom")
class MultiViewLayer(tf.keras.layers.Layer):
    """Generates 8 orientations (4 rotations + 4 flips) of the input batch."""
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, inputs):
        # inputs: (Batch, H, W, 3)
        rot0 = inputs
        rot90 = tf.image.rot90(inputs, k=1)
        rot180 = tf.image.rot90(inputs, k=2)
        rot270 = tf.image.rot90(inputs, k=3)

        flip0 = tf.image.flip_left_right(rot0)
        flip90 = tf.image.flip_left_right(rot90)
        flip180 = tf.image.flip_left_right(rot180)
        flip270 = tf.image.flip_left_right(rot270)

        # Stack: (8, Batch, H, W, 3)
        views = tf.stack([rot0, rot90, rot180, rot270, flip0, flip90, flip180, flip270], axis=0)

        # Flatten: (8*Batch, H, W, 3)
        s = tf.shape(inputs)
        return tf.reshape(views, [8 * s[0], s[1], s[2], s[3]])

    def compute_output_shape(self, input_shape):
        batch = input_shape[0] * 8 if input_shape[0] is not None else None
        return (batch, input_shape[1], input_shape[2], input_shape[3])

@tf.keras.utils.register_keras_serializable(package="Custom")
class MultiViewAverage(tf.keras.layers.Layer):
    """Averages features or predictions across the 8 orientations."""
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, inputs):
        # inputs: (8*Batch, D)
        s = tf.shape(inputs)
        d = inputs.shape[-1]
        # Reshape to (8, Batch, D)
        x = tf.reshape(inputs, [8, s[0] // 8, d])
        return tf.reduce_mean(x, axis=0)

    def compute_output_shape(self, input_shape):
        batch = input_shape[0] // 8 if input_shape[0] is not None else None
        return (batch, input_shape[1])


@tf.keras.utils.register_keras_serializable(package="Custom")
class BenannePartExtractor(tf.keras.layers.Layer):
    """Create benanne-style views and 45x45 aligned parts."""
    def __init__(self, view_size: int = 69, part_size: int = 45, **kwargs):
        super().__init__(**kwargs)
        self.view_size = view_size
        self.part_size = part_size

    def call(self, inputs):
        regular_view = tf.image.resize(inputs, [self.view_size, self.view_size])
        rotated_view = tf.image.resize(_rotate_batch(inputs, 45.0), [self.view_size, self.view_size])

        views = [
            regular_view,
            tf.image.flip_left_right(regular_view),
            rotated_view,
            tf.image.flip_left_right(rotated_view),
        ]

        parts = []
        ps = self.part_size
        for view in views:
            parts.append(view[:, :ps, :ps, :])
            parts.append(tf.image.rot90(view[:, :ps, -ps:, :], k=1))
            parts.append(tf.image.rot90(view[:, -ps:, -ps:, :], k=2))
            parts.append(tf.image.rot90(view[:, -ps:, :ps, :], k=3))

        return tf.concat(parts, axis=0)

    def get_config(self):
        config = super().get_config()
        config.update({"view_size": self.view_size, "part_size": self.part_size})
        return config


@tf.keras.utils.register_keras_serializable(package="Custom")
class PartFeatureMerge(tf.keras.layers.Layer):
    """Merge flattened part features back into per-example features."""
    def __init__(self, num_parts: int = 16, **kwargs):
        super().__init__(**kwargs)
        self.num_parts = num_parts

    def call(self, inputs):
        shape = tf.shape(inputs)
        feature_dim = inputs.shape[-1]
        merged = tf.reshape(inputs, [self.num_parts, shape[0] // self.num_parts, feature_dim])
        merged = tf.transpose(merged, [1, 0, 2])
        return tf.reshape(merged, [shape[0] // self.num_parts, self.num_parts * feature_dim])

    def get_config(self):
        config = super().get_config()
        config["num_parts"] = self.num_parts
        return config


@tf.keras.utils.register_keras_serializable(package="Custom")
class MaxoutDense(tf.keras.layers.Layer):
    """Dense layer with maxout pooling across linear pieces."""
    def __init__(self, units: int, pieces: int = 2, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.pieces = pieces
        self.projection = tf.keras.layers.Dense(units * pieces, activation=None, dtype='float32')

    def call(self, inputs):
        outputs = self.projection(inputs)
        dynamic_shape = tf.shape(outputs)
        outputs = tf.reshape(outputs, [dynamic_shape[0], self.units, self.pieces])
        return tf.reduce_max(outputs, axis=-1)

    def get_config(self):
        config = super().get_config()
        config.update({"units": self.units, "pieces": self.pieces})
        return config


@tf.keras.utils.register_keras_serializable(package="Custom")
class GalaxyOutputLayer(tf.keras.layers.Layer):
    """Normalizes per-question answers and applies Galaxy Zoo tree weights."""
    def __init__(self, epsilon: float = 1e-7, **kwargs):
        super().__init__(**kwargs)
        self.epsilon = epsilon

    def call(self, inputs):
        positive = tf.nn.softplus(inputs) + self.epsilon
        question_probs = []
        for start, end in QUESTION_SLICES:
            question = positive[:, start:end]
            question_sum = tf.reduce_sum(question, axis=1, keepdims=True)
            question_probs.append(question / question_sum)

        outputs = tf.concat(question_probs, axis=1)
        for start, end, parent_idx in SCALING_SEQUENCE:
            parent_prob = outputs[:, parent_idx:parent_idx + 1]
            scaled_slice = outputs[:, start:end] * parent_prob
            outputs = tf.concat(
                [outputs[:, :start], scaled_slice, outputs[:, end:]],
                axis=1,
            )

        return outputs

    def get_config(self):
        config = super().get_config()
        config["epsilon"] = self.epsilon
        return config


def build_regression_model(
    architecture: str = 'EfficientNetV2B2',
    multi_view: bool = False,
) -> tuple[tf.keras.Model, tf.keras.Model]:
    """Build unified regression model: Predicts all 37 Galaxy Zoo probabilities.

    If multi_view is True, the model processes 8 rotations/flips and averages them.
    """
    inputs = tf.keras.Input(shape=(None, None, 3), name='image_input')

    if architecture == 'BenanneNetTF':
        x = BenannePartExtractor(name='benanne_parts')(inputs)
        x = tf.keras.layers.Conv2D(32, 6, activation='relu', padding='valid', name='conv1')(x)
        x = tf.keras.layers.MaxPooling2D(pool_size=2, name='pool1')(x)
        x = tf.keras.layers.Conv2D(64, 5, activation='relu', padding='valid', name='conv2')(x)
        x = tf.keras.layers.MaxPooling2D(pool_size=2, name='pool2')(x)
        x = tf.keras.layers.Conv2D(128, 3, activation='relu', padding='valid', name='conv3')(x)
        x = tf.keras.layers.Conv2D(128, 3, activation='relu', padding='valid', name='conv4')(x)
        x = tf.keras.layers.MaxPooling2D(pool_size=2, name='pool4')(x)
        x = tf.keras.layers.Flatten(name='flatten_parts')(x)
        x = PartFeatureMerge(name='merge_parts')(x)
        x = tf.keras.layers.Dropout(0.5, name='dropout1')(x)
        x = MaxoutDense(2048, pieces=2, name='maxout1')(x)
        x = tf.keras.layers.Dropout(0.5, name='dropout2')(x)
        x = MaxoutDense(2048, pieces=2, name='maxout2')(x)
        x = tf.keras.layers.Dropout(0.5, name='dropout3')(x)
        logits = tf.keras.layers.Dense(37, activation=None, dtype='float32', name='regression_logits')(x)
        outputs = GalaxyOutputLayer(name='regression_output')(logits)
        model = tf.keras.Model(inputs=inputs, outputs=outputs, name='GalaxyNet_BenanneNetTF')
        return model, None

    x = inputs
    if multi_view:
        x = MultiViewLayer()(x)

    base_model = _get_backbone(architecture, x)
    x = tf.keras.layers.GlobalAveragePooling2D(name='gap')(base_model.output)

    if multi_view:
        x = MultiViewAverage()(x)

    x = tf.keras.layers.BatchNormalization(name='bn1')(x)
    x = tf.keras.layers.Dense(512, name='dense1')(x)
    x = tf.keras.layers.BatchNormalization(name='bn2')(x)
    x = tf.keras.layers.Activation('gelu', name='gelu1')(x)
    x = tf.keras.layers.Dropout(0.4, name='dropout1')(x)

    logits = tf.keras.layers.Dense(37, activation=None, dtype='float32', name='regression_logits')(x)
    outputs = GalaxyOutputLayer(name='regression_output')(logits)

    model = tf.keras.Model(
        inputs=inputs,
        outputs=outputs,
        name=f'GalaxyNet_UnifiedRegression_{architecture}_MV' if multi_view else f'GalaxyNet_UnifiedRegression_{architecture}',
    )
    return model, base_model


def unfreeze_top_layers(base_model: tf.keras.Model, last_n: int) -> int:
    """Gradually unfreezes the last N layers of the base model for fine-tuning.

    All layers before the last N are frozen (not trainable).
    Returns the number of unfrozen layers (those with trainable weights).
    """
    if base_model is None:
        return 0
    base_model.trainable = True
    total_layers = len(base_model.layers)
    freeze_up_to = max(0, total_layers - last_n)
    for layer in base_model.layers[:freeze_up_to]:
        layer.trainable = False
    # Unfreeze everything after the boundary
    for layer in base_model.layers[freeze_up_to:]:
        layer.trainable = True
    # Count layers that are actually trainable and have weights
    unfrozen = sum(1 for l in base_model.layers[freeze_up_to:] if len(l.weights) > 0)
    return unfrozen


def freeze_base(base_model: tf.keras.Model) -> None:
    """Freeze all layers of the base model (for warmup phase)."""
    if base_model is not None:
        base_model.trainable = False


# ============================================================
# START OF dataset.py
# ============================================================






COLOUR_CHANNEL_WEIGHTS = tf.constant(
    [-0.0148366, -0.01253134, -0.01040762],
    dtype=tf.float32,
)


# ══════════════════════════════════════════════════════════════
# LABEL DETERMINATION (Regression - 37 Targets)
# ══════════════════════════════════════════════════════════════

def generate_labels_df(solutions_csv: Path, image_dir: Path) -> pd.DataFrame:
    """Generate 37-target DataFrame from Galaxy Zoo solutions CSV for Regression."""
    df = pd.read_csv(solutions_csv)

    # Automatically extract all 37 Class probability columns
    target_cols = [col for col in df.columns if col.startswith('Class')]
    if len(target_cols) != 37:
        print(f"WARNING: Expected 37 Class columns, found {len(target_cols)}")

    df['image_path'] = df['GalaxyID'].astype(str).apply(lambda gid: str(image_dir / f'{gid}.jpg'))

    # Check physical file existence to prune missing downloads
    df = df[df['image_path'].apply(lambda p: Path(p).exists())].copy()

    keep_cols = ['GalaxyID', 'image_path'] + target_cols
    return df[keep_cols], target_cols


# ══════════════════════════════════════════════════════════════
# IMAGE LOADING & BASE PREPROCESSING
# ══════════════════════════════════════════════════════════════

def _smart_crop(image: tf.Tensor, ratio: float = 0.75) -> tf.Tensor:
    """Crops the image around its brightness centroid instead of the static center.

    Uses a Gaussian center prior to avoid latching onto background stars.
    """
    shape = tf.shape(image)
    h_int, w_int = shape[0], shape[1]
    h, w = tf.cast(h_int, tf.float32), tf.cast(w_int, tf.float32)

    # Calculate centroid using green channel (brightness approximation)
    img_green = image[..., 1]

    # Apply Gaussian center prior (sigma^2 = 5000 as in benanne solution)
    yy_grid, xx_grid = tf.meshgrid(tf.range(h_int), tf.range(w_int), indexing='ij')
    yy_grid = tf.cast(yy_grid, tf.float32)
    xx_grid = tf.cast(xx_grid, tf.float32)

    prior = tf.exp(-((yy_grid - h/2.0)**2 + (xx_grid - w/2.0)**2) / 5000.0)
    img_weighted = img_green * prior

    total_flux = tf.reduce_sum(img_weighted) + 1e-6

    # Weighted average coordinates
    cy = tf.reduce_sum(tf.reduce_sum(img_weighted, axis=1) * tf.cast(tf.range(h_int), tf.float32)) / total_flux
    cx = tf.reduce_sum(tf.reduce_sum(img_weighted, axis=0) * tf.cast(tf.range(w_int), tf.float32)) / total_flux

    # Clip centroid to keep the crop mostly within image bounds
    cy = tf.clip_by_value(cy, h * 0.1, h * 0.9)
    cx = tf.clip_by_value(cx, w * 0.1, w * 0.9)

    # Crop size
    ch = tf.cast(h * ratio, tf.int32)
    cw = tf.cast(w * ratio, tf.int32)

    offset_h = tf.cast(cy - tf.cast(ch, tf.float32) / 2.0, tf.int32)
    offset_w = tf.cast(cx - tf.cast(cw, tf.float32) / 2.0, tf.int32)

    # Final clamping to ensure valid crop
    offset_h = tf.clip_by_value(offset_h, 0, h_int - ch)
    offset_w = tf.clip_by_value(offset_w, 0, w_int - cw)

    return tf.image.crop_to_bounding_box(image, offset_h, offset_w, ch, cw)


def load_and_preprocess_image(path: tf.Tensor, label: tf.Tensor, image_size: int,
                               center_crop_ratio: float = 0.75):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.cast(img, tf.float32)
    img = _smart_crop(img, ratio=center_crop_ratio)
    img = tf.image.resize(img, [image_size, image_size])
    img = tf.clip_by_value(img, 0.0, 255.0)
    return img, label


# ══════════════════════════════════════════════════════════════
# AUGMENTATION
# ══════════════════════════════════════════════════════════════

def apply_cutout(image: tf.Tensor, n_holes: int = 2, max_size_ratio: float = 0.20) -> tf.Tensor:
    shape = tf.shape(image)
    h, w = shape[0], shape[1]
    img_mean = tf.reduce_mean(image)

    mask = tf.ones_like(image)
    for _ in range(n_holes):
        hole_size_h = tf.random.uniform([], minval=tf.cast(tf.cast(h, tf.float32) * 0.05, tf.int32),
                                         maxval=tf.maximum(tf.cast(tf.cast(h, tf.float32) * max_size_ratio, tf.int32), 2),
                                         dtype=tf.int32)
        hole_size_w = tf.random.uniform([], minval=tf.cast(tf.cast(w, tf.float32) * 0.05, tf.int32),
                                         maxval=tf.maximum(tf.cast(tf.cast(w, tf.float32) * max_size_ratio, tf.int32), 2),
                                         dtype=tf.int32)
        cy = tf.random.uniform([], minval=hole_size_h // 2, maxval=h - hole_size_h // 2, dtype=tf.int32)
        cx = tf.random.uniform([], minval=hole_size_w // 2, maxval=w - hole_size_w // 2, dtype=tf.int32)

        y1 = tf.maximum(cy - hole_size_h // 2, 0)
        y2 = tf.minimum(cy + hole_size_h // 2, h)
        x1 = tf.maximum(cx - hole_size_w // 2, 0)
        x2 = tf.minimum(cx + hole_size_w // 2, w)

        top_pad = y1
        bottom_pad = h - y2
        left_pad = x1
        right_pad = w - x2
        hole_h = y2 - y1
        hole_w = x2 - x1

        hole = tf.zeros([hole_h, hole_w, 3])
        hole = tf.pad(hole, [[top_pad, bottom_pad], [left_pad, right_pad], [0, 0]], constant_values=1.0)
        mask = mask * hole

    image = image * mask + img_mean * (1.0 - mask)
    return image


def apply_poisson_noise(image: tf.Tensor, scale: float = 25.0) -> tf.Tensor:
    img_norm = image / 255.0
    img_scaled = img_norm * scale
    noisy = tf.random.poisson(shape=[], lam=tf.maximum(img_scaled, 1e-6))
    noisy = noisy / scale * 255.0
    return tf.clip_by_value(noisy, 0.0, 255.0)


def apply_gaussian_blur(image: tf.Tensor, sigma: float = 1.0) -> tf.Tensor:
    kernel_size = tf.cast(tf.math.ceil(sigma * 3.0) * 2 + 1, tf.int32)
    kernel_size = tf.maximum(kernel_size, 3)
    half = tf.cast(kernel_size // 2, tf.float32)
    x = tf.range(-half, half + 1, dtype=tf.float32)
    kernel_1d = tf.exp(-x ** 2 / (2.0 * sigma ** 2))
    kernel_1d = kernel_1d / tf.reduce_sum(kernel_1d)
    kernel_2d = tf.tensordot(kernel_1d, kernel_1d, axes=0)
    kernel_2d = kernel_2d[:, :, tf.newaxis, tf.newaxis]
    kernel_2d = tf.tile(kernel_2d, [1, 1, 3, 1])

    image_4d = tf.expand_dims(image, 0)
    blurred = tf.nn.depthwise_conv2d(image_4d, kernel_2d, strides=[1, 1, 1, 1], padding='SAME')
    return tf.squeeze(blurred, 0)


def apply_affine_transform(
    image: tf.Tensor,
    angle: tf.Tensor,
    zoom: tf.Tensor = tf.constant(1.0, dtype=tf.float32),
    translate_x: tf.Tensor = tf.constant(0.0, dtype=tf.float32),
    translate_y: tf.Tensor = tf.constant(0.0, dtype=tf.float32),
    flip_left_right: tf.Tensor = tf.constant(False),
) -> tf.Tensor:
    """Apply a deterministic affine transform in the style of benanne's pipeline."""
    image = tf.cond(flip_left_right, lambda: tf.image.flip_left_right(image), lambda: image)

    cos_a = tf.cos(angle) / zoom
    sin_a = tf.sin(angle) / zoom
    h = tf.cast(tf.shape(image)[0], tf.float32)
    w = tf.cast(tf.shape(image)[1], tf.float32)
    cx = (w - 1.0) / 2.0
    cy = (h - 1.0) / 2.0

    a0 = cos_a
    a1 = sin_a
    a2 = cx - a0 * cx - a1 * cy + translate_x
    b0 = -sin_a
    b1 = cos_a
    b2 = cy - b0 * cx - b1 * cy + translate_y

    transform = tf.reshape(tf.stack([a0, a1, a2, b0, b1, b2, 0.0, 0.0]), [1, 8])
    image_4d = tf.expand_dims(image, 0)
    transformed = tf.raw_ops.ImageProjectiveTransformV3(
        images=image_4d,
        transforms=tf.cast(transform, tf.float32),
        output_shape=tf.shape(image)[:2],
        fill_value=0.0,
        interpolation='BILINEAR',
        fill_mode='REFLECT',
    )
    return tf.squeeze(transformed, 0)


def apply_colour_perturbation(image: tf.Tensor, std: float = 0.5) -> tf.Tensor:
    image = image / 255.0
    alpha = tf.random.normal([], stddev=std, dtype=tf.float32)
    image = tf.clip_by_value(image + alpha * COLOUR_CHANNEL_WEIGHTS, 0.0, 1.0)
    return image * 255.0


def augment_image(image: tf.Tensor, label: tf.Tensor):
    h = tf.cast(tf.shape(image)[0], tf.float32)
    w = tf.cast(tf.shape(image)[1], tf.float32)
    scale_x = w / 424.0
    scale_y = h / 424.0

    angle = tf.random.uniform([], 0.0, 2.0 * math.pi)
    log_zoom = tf.random.uniform([], math.log(1.0 / 1.3), math.log(1.3))
    zoom = tf.exp(log_zoom)
    translate_x = tf.random.uniform([], -4.0, 4.0) * scale_x
    translate_y = tf.random.uniform([], -4.0, 4.0) * scale_y
    flip_left_right = tf.random.uniform([]) > 0.5

    image = apply_affine_transform(
        image,
        angle=angle,
        zoom=zoom,
        translate_x=translate_x,
        translate_y=translate_y,
        flip_left_right=flip_left_right,
    )
    image = apply_colour_perturbation(image, std=0.5)
    image = tf.clip_by_value(image, 0.0, 255.0)
    return image, label


def apply_tta_transform(image: tf.Tensor, label: tf.Tensor, tta_index: int):
    """Apply deterministic benanne-style TTA: 10 rotations x 3 zooms x 2 flips."""
    zooms = (1.0, 1.0 / 1.2, 1.2)
    zoom_index = (tta_index // 20) % len(zooms)
    transform_index = tta_index % 20
    angle_index = transform_index // 2
    flip_left_right = tf.equal(transform_index % 2, 1)
    angle = tf.cast(angle_index, tf.float32) * (2.0 * math.pi / 10.0)

    image = apply_affine_transform(
        image,
        angle=angle,
        zoom=tf.constant(zooms[zoom_index], dtype=tf.float32),
        flip_left_right=flip_left_right,
    )
    return image, label


# ══════════════════════════════════════════════════════════════
# DATASET BUILDERS
# ══════════════════════════════════════════════════════════════

def build_dataset(
    image_paths: np.ndarray,
    labels: np.ndarray,
    image_size: int,
    batch_size: int,
    center_crop_ratio: float = 0.75,
    augment: bool = False,
    shuffle: bool = False,
    cache: bool = False,
    drop_remainder: bool = False,
    tta_index: int | None = None,
) -> tf.data.Dataset:
    """Build a tf.data.Dataset mapping paths and 37-node target vectors."""
    if augment and tta_index is not None:
        raise ValueError("Training augmentation and deterministic TTA are mutually exclusive.")

    ds = tf.data.Dataset.from_tensor_slices((image_paths, labels))
    ds = ds.map(
        lambda p, y: load_and_preprocess_image(p, y, image_size, center_crop_ratio),
        num_parallel_calls=tf.data.AUTOTUNE,
    )

    if shuffle:
        ds = ds.shuffle(buffer_size=min(len(image_paths), 10000), reshuffle_each_iteration=True)

    if augment:
        ds = ds.map(lambda i, l: augment_image(i, l), num_parallel_calls=tf.data.AUTOTUNE)

    if tta_index is not None:
        ds = ds.map(
            lambda i, l: apply_tta_transform(i, l, tta_index),
            num_parallel_calls=tf.data.AUTOTUNE,
        )

    if cache:
        ds = ds.cache()

    ds = ds.batch(batch_size, drop_remainder=drop_remainder).prefetch(tf.data.AUTOTUNE)
    return ds


# ══════════════════════════════════════════════════════════════
# SPLITTING & ORCHESTRATION
# ══════════════════════════════════════════════════════════════

def build_datasets(labels_df: pd.DataFrame, config: Config):
    """Build train/validation/test splits for regression."""
    if config.legacy_ordered_split:
        ordered_df = labels_df.sort_values('GalaxyID').reset_index(drop=True)
        train_fraction = 1.0 - config.val_split - config.test_split
        train_end = int(len(ordered_df) * train_fraction)
        val_end = int(len(ordered_df) * (1.0 - config.test_split))
        train_df = ordered_df.iloc[:train_end].reset_index(drop=True)
        val_df = ordered_df.iloc[train_end:val_end].reset_index(drop=True)
        test_df = ordered_df.iloc[val_end:].reset_index(drop=True)
    else:
        train_df, temp_df = train_test_split(
            labels_df,
            test_size=config.val_split + config.test_split,
            random_state=config.seed,
        )
        if config.test_split > 0:
            test_ratio_of_temp = config.test_split / (config.val_split + config.test_split)
            val_df, test_df = train_test_split(
                temp_df,
                test_size=test_ratio_of_temp,
                random_state=config.seed,
            )
        else:
            val_df = temp_df
            test_df = temp_df.iloc[0:0].copy()

        train_df = train_df.reset_index(drop=True)
        val_df = val_df.reset_index(drop=True)
        test_df = test_df.reset_index(drop=True)

    split_info = {
        'train_size': len(train_df),
        'val_size': len(val_df),
        'test_size': len(test_df),
        'total_labeled_images': len(labels_df),
    }

    return split_info, (train_df, val_df, test_df)


# ============================================================
# START OF evaluate.py
# ============================================================


import csv




def calculate_rmse(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """Calculate the global Root Mean Squared Error over all targets."""
    mse = np.mean(np.square(y_true - y_pred))
    return np.sqrt(mse)


def load_inference_model(model_path: Path) -> tf.keras.Model:
    custom_objects = {
        'RMSELoss': RMSELoss,
        'HierarchicalRMSELoss': HierarchicalRMSELoss,
        'rmse_metric': rmse_metric,
        'MultiViewLayer': MultiViewLayer,
        'MultiViewAverage': MultiViewAverage,
        'GalaxyOutputLayer': GalaxyOutputLayer,
        'BenannePartExtractor': BenannePartExtractor,
        'PartFeatureMerge': PartFeatureMerge,
        'MaxoutDense': MaxoutDense,
    }
    return tf.keras.models.load_model(
        model_path,
        custom_objects=custom_objects,
        compile=False,
    )


def predict_tta(model: tf.keras.Model, test_paths: np.ndarray, config: Config) -> np.ndarray:
    """Run Test-Time Augmentation (TTA) and return averaged predictions."""
    print(f"\n[Evaluation] Running TTA ({config.tta_n_augments} passes)...")

    # Dummy labels for the dataset builder
    dummy_labels = np.zeros((len(test_paths), 37), dtype=np.float32)

    tta_preds = []

    # Pass 1: Original (unaugmented) center crop
    ds_base = build_dataset(
        test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
        drop_remainder=False, tta_index=0,
    )
    base_preds = model.predict(ds_base, verbose=1)
    tta_preds.append(base_preds)

    # Passes 2 to N: Augmented crops/rotations
    for i in range(config.tta_n_augments - 1):
        ds_aug = build_dataset(
            test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
            center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
            drop_remainder=False, tta_index=i + 1,
        )
        preds = model.predict(ds_aug, verbose=0)
        tta_preds.append(preds)
        print(f"  TTA pass {i+2}/{config.tta_n_augments} completed.")

    return np.mean(tta_preds, axis=0)


def _load_submission_template(submission_template_path: Path) -> tuple[list[str], list[int]]:
    if submission_template_path.suffix == '.zip':
        with zipfile.ZipFile(submission_template_path, 'r') as zf:
            csv_name = zf.namelist()[0]
            with zf.open(csv_name, 'r') as handle:
                lines = [line.decode('utf-8').strip() for line in handle]
    else:
        with submission_template_path.open('r', encoding='utf-8') as handle:
            lines = [line.strip() for line in handle]

    reader = csv.reader(lines)
    rows = list(reader)
    header = rows[0]
    galaxy_ids = [int(row[0]) for row in rows[1:] if row]
    return header, galaxy_ids


def generate_competition_submission(
    config: Config,
    test_image_dir: Path,
    target_cols: list[str],
    submission_template_path: Path,
) -> Path | None:
    output_dir = config.output_dir
    model_path = output_dir / 'unified_best.keras'
    if not model_path.exists():
        print(f"Error: Unified model not found at {model_path}")
        return None

    header, galaxy_ids = _load_submission_template(submission_template_path)
    expected_header = ['GalaxyID'] + target_cols
    if header != expected_header:
        raise ValueError('Submission template header does not match expected competition columns.')

    test_paths = np.array([str(test_image_dir / f'{galaxy_id}.jpg') for galaxy_id in galaxy_ids])
    missing_paths = [path for path in test_paths if not Path(path).exists()]
    if missing_paths:
        raise FileNotFoundError(f'Missing {len(missing_paths)} competition test images.')

    print('\n' + '=' * 60)
    print('COMPETITION SUBMISSION')
    print('=' * 60)
    print(f'Predicting {len(test_paths)} competition test images...')

    model = load_inference_model(model_path)
    predictions = predict_tta(model, test_paths, config)
    if predictions.shape != (len(galaxy_ids), len(target_cols)):
        raise ValueError(
            f'Unexpected prediction shape {predictions.shape}, expected {(len(galaxy_ids), len(target_cols))}.'
        )

    submission_df = pd.DataFrame(predictions, columns=target_cols)
    submission_df.insert(0, 'GalaxyID', galaxy_ids)

    submission_path = output_dir / config.submission_filename
    submission_df.to_csv(
        submission_path,
        index=False,
        compression='gzip',
        float_format='%.6f',
    )
    print(f'Submission written to {submission_path}')
    return submission_path


def evaluate_regression(config: Config, test_df: pd.DataFrame, target_cols: list[str], split_name: str = 'test'):
    """Evaluate the single unified regression model using RMSE."""
    output_dir = config.output_dir
    model_path = output_dir / 'unified_best.keras'

    if not model_path.exists():
        print(f"Error: Unified model not found at {model_path}")
        return

    print('\n' + '=' * 60)
    print('EVALUATION: REGRESSION RMSE')
    print('=' * 60)

    # Load model
    print("Loading unified model...")
    model = load_inference_model(model_path)

    test_paths = test_df['image_path'].values
    y_true = test_df[target_cols].values.astype(np.float32)

    # Standard Prediction (No TTA)
    dummy_labels = np.zeros_like(y_true)
    ds_test = build_dataset(
        test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
        drop_remainder=False,
    )

    print("\nRunning standard evaluation (1-pass)...")
    y_pred_std = model.predict(ds_test, verbose=1)
    rmse_std = calculate_rmse(y_true, y_pred_std)

    # TTA Prediction
    y_pred_tta = predict_tta(model, test_paths, config)
    rmse_tta = calculate_rmse(y_true, y_pred_tta)

    # Report
    print('\n' + '-' * 40)
    print(f"{split_name.upper()} METRICS")
    print('-' * 40)
    print(f"  RMSE (Single Pass): {rmse_std:.5f}")
    print(f"  RMSE (TTA {config.tta_n_augments}x):     {rmse_tta:.5f}")
    print('-' * 40)

    # Save results
    results = {
        'split_name': split_name,
        'split_size': len(test_df),
        'rmse_standard': float(rmse_std),
        'rmse_tta': float(rmse_tta),
    }

    with open(output_dir / 'evaluation_results.json', 'w') as f:
        json.dump(results, f, indent=2)

    print(f"\nEvaluation complete. Results saved to {output_dir / 'evaluation_results.json'}")


# ============================================================
# START OF train.py
# ============================================================



# Suppress noisy TF/Keras logs before importing TensorFlow.
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['ABSL_LOGGING_LEVEL'] = 'error'


tf.keras.utils.disable_interactive_logging()



class ConciseLogging(tf.keras.callbacks.Callback):
    """Minimal logging to prevent log flooding during long regression runs."""
    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}
        lr = self.model.optimizer.learning_rate
        if isinstance(lr, tf.keras.optimizers.schedules.LearningRateSchedule):
            lr_val = float(lr(self.model.optimizer.iterations))
        else:
            # Handle standard variables or distributed MirroredVariables
            lr_val = float(tf.convert_to_tensor(lr))

        print(f"Epoch {epoch+1:02d} | Loss: {logs.get('loss', 0):.4f} | "
              f"Val RMSE: {logs.get('val_rmse_metric', 0):.4f} | LR: {lr_val:.1e}")


def train_unified_regression(config: Config, solutions_csv: Path, image_dir: Path):
    """Unified progressive resizing training loop for 37-node regression."""
    output_dir = config.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Strategy Initialization ──
    strategy = get_strategy()

    # ── Dataset Preparation ──
    df, target_cols = generate_labels_df(solutions_csv, image_dir)
    split_info, (train_df, val_df, test_df) = build_datasets(df, config)

    train_paths = train_df['image_path'].values
    train_labels = train_df[target_cols].values.astype(np.float32)
    val_paths = val_df['image_path'].values
    val_labels = val_df[target_cols].values.astype(np.float32)
    uses_benanne_schedule = config.architecture == 'BenanneNetTF'

    # Scale batch sizes by number of TPU replicas
    bs1 = config.get_scaled_batch_size(config.batch_size_phase1, strategy)
    bs2 = config.get_scaled_batch_size(config.batch_size_phase2, strategy)
    bs3 = config.get_scaled_batch_size(config.batch_size_phase3, strategy)


    # ── Model & Strategy Scope ──
    with strategy.scope():
        model, base_model = build_regression_model(config.architecture, multi_view=config.multi_view)
        loss_fn = RMSELoss()

    def compile_for_phase(phase_lr: float, steps_per_epoch: int | None = None):
        with strategy.scope():
            if uses_benanne_schedule:
                optimizer = tf.keras.optimizers.SGD(
                    learning_rate=phase_lr,
                    momentum=0.9,
                    nesterov=True,
                )
            elif steps_per_epoch is None:
                optimizer = tf.keras.optimizers.Adam(phase_lr)
            else:
                optimizer = tf.keras.optimizers.Adam(
                    build_cosine_restart_schedule(
                        phase_lr,
                        steps_per_epoch,
                        restart_epochs=5,
                    ),
                    clipnorm=1.0,
                )
            model.compile(optimizer=optimizer, loss=loss_fn, metrics=[rmse_metric])
            return model

    # ── Phase 1: Warmup (Fixed layers, 128px) ──
    print(f'\n[Phase 1] Warmup (Frozen Backbone, {config.image_size_phase1}px)')
    freeze_base(base_model)

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase1, bs1,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
        drop_remainder=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase1, bs1,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
    )

    train_model = compile_for_phase(config.warmup_lr)

    train_model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.warmup_epochs,
        callbacks=[ConciseLogging()],
        verbose=0,
    )

    # ── Phase 2: Mid-tune (Partial unfreeze, 192px) ──
    print(f'\n[Phase 2] Mid-tune (Unfreeze {config.unfreeze_phase2} layers, {config.image_size_phase2}px)')
    unfreeze_top_layers(base_model, config.unfreeze_phase2)

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase2, bs2,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
        drop_remainder=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase2, bs2,
        center_crop_ratio=config.center_crop_ratio,
    )

    steps_per_epoch = len(train_paths) // bs2
    train_model = compile_for_phase(
        config.midtune_lr,
        None if uses_benanne_schedule else steps_per_epoch,
    )

    train_model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.midtune_epochs,
        callbacks=[ConciseLogging()],
        verbose=0,
    )

    # ── Phase 3: Fine-tune (More unfreeze, 384px) ──
    print(f'\n[Phase 3] Fine-tune (Unfreeze {config.unfreeze_phase3} layers, {config.image_size_phase3}px)')
    unfreeze_top_layers(base_model, config.unfreeze_phase3)

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase3, bs3,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
        drop_remainder=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase3, bs3,
        center_crop_ratio=config.center_crop_ratio,
    )

    steps_per_epoch = len(train_paths) // bs3
    train_model = compile_for_phase(
        config.finetune_lr,
        None if uses_benanne_schedule else steps_per_epoch,
    )

    train_model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.finetune_epochs,
        callbacks=[
            tf.keras.callbacks.ModelCheckpoint(
                str(output_dir / 'unified_best.keras'),
                monitor='val_rmse_metric', save_best_only=True, mode='min',
                verbose=0
            ),
            ConciseLogging(),
        ],
        verbose=0,
    )

    # ── SWA ──
    if config.swa_epochs > 0 and not uses_benanne_schedule:
        print('\n[SWA Phase]')
        train_ds_swa = build_dataset(
            train_paths, train_labels, config.image_size_phase3, bs3,
            center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=True,
            drop_remainder=True,
        )
        with strategy.scope():
            model = run_swa(model, train_ds_swa, config.swa_epochs, config.swa_lr_high, config.swa_lr_low)
            model.save(str(output_dir / 'unified_best.keras'))

    # Save details
    save_json(output_dir / 'split_info.json', split_info)

    # Cleanup
    tf.keras.backend.clear_session()
    gc.collect()

    eval_df = test_df if len(test_df) > 0 else val_df
    eval_name = 'test' if len(test_df) > 0 else 'validation'
    return eval_df, target_cols, eval_name


def main():
    t0 = time.time()
    config = Config()

    setup_environment(config)

    if is_kaggle_runtime():
        solutions_csv, image_dir, test_image_dir, submission_template_path = setup_kaggle_environment(config)
    else:
        solutions_csv, image_dir, test_image_dir, submission_template_path = setup_local_environment(config)

    # Run pipeline
    eval_df, target_cols, eval_name = train_unified_regression(config, solutions_csv, image_dir)

    print(f"\nTraining pipeline completed in {(time.time() - t0) / 60:.1f} minutes.")

    evaluate_regression(config, eval_df, target_cols, split_name=eval_name)

    if test_image_dir.exists():
        from evaluate import generate_competition_submission

        generate_competition_submission(
            config=config,
            test_image_dir=test_image_dir,
            target_cols=target_cols,
            submission_template_path=submission_template_path,
        )


if __name__ == '__main__':
    main()
