# AUTO-GENERATED KAGGLE BUNDLE — GalaxyNet V25 Cascade Pipeline
# This file merges modular components for Kaggle compatibility.
# Generated by scripts/consolidate.py

from __future__ import annotations

import argparse
import datetime
import gc
import json
import math
import multiprocessing
import os
import pickle
import random
import subprocess
import sys
import time
import zipfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Tuple

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import (
    brier_score_loss,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split

try:
    import tensorflow_addons as tfa
except Exception:
    tfa = None

try:
    import xgboost as xgb
except ImportError:
    xgb = None

# ============================================================
# START OF config.py
# ============================================================




@dataclass
class Config:
    # ── Paths ──────────────────────────────────────────────────
    kaggle_input_dir: Path = Path('/kaggle/input/competitions/galaxy-zoo-the-galaxy-challenge')
    kaggle_temp_dir: Path = Path('/kaggle/temp')
    output_dir: Path = Path('/kaggle/working/outputs')

    # ── Image resolution curriculum ────────────────────────────
    image_size_phase1: int = 128
    image_size_phase2: int = 192
    image_size_phase3: int = 288
    center_crop_ratio: float = 0.75

    # ── Batch sizes (per phase, tuned for P100 16GB) ───────────
    batch_size_phase1: int = 64
    batch_size_phase2: int = 32
    batch_size_phase3: int = 16
    grad_accumulation_steps: int = 1  # Native batching to avoid tf.Variable placement errors

    # ── Data split ─────────────────────────────────────────────
    seed: int = 42
    val_split: float = 0.15
    test_split: float = 0.15

    # ── Model Architecture ─────────────────────────────────────
    architecture: str = 'EfficientNetV2B2'

    # ── Training Schedule ──────────────────────────────────────
    warmup_epochs: int = 12
    midtune_epochs: int = 10
    finetune_epochs: int = 25

    warmup_lr: float = 3e-4
    midtune_lr: float = 3e-5
    finetune_lr: float = 8e-6

    unfreeze_phase2: int = 50
    unfreeze_phase3: int = 80

    # ── Augmentation ───────────────────────────────────────────
    mixup_alpha: float = 0.4
    mixup_prob: float = 0.5
    cutout_n_holes: int = 2
    cutout_max_size_ratio: float = 0.20

    # ── Astronomy-Specific Augmentations (V26) ─────────────────
    augment_poisson_scale: float = 25.0   # higher = less noise
    augment_poisson_prob: float = 0.3
    augment_blur_prob: float = 0.2
    augment_blur_sigma_range: Tuple[float, float] = (0.5, 2.0)

    # ── SWA ────────────────────────────────────────────────────
    swa_epochs: int = 5
    swa_lr_high: float = 1e-5
    swa_lr_low: float = 5e-6

    # ── TTA ────────────────────────────────────────────────────
    tta_n_augments: int = 16

    # ── Runtime ────────────────────────────────────────────────
    enable_mixed_precision: bool = True


# ============================================================
# START OF utils.py
# ============================================================






def set_global_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)


def setup_environment(config: Config) -> None:
    set_global_seed(config.seed)

    if config.enable_mixed_precision:
        tf.keras.mixed_precision.set_global_policy('mixed_float16')

    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        print(f'GPU available: {gpus}')
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    else:
        print('No GPU detected — running on CPU')


def find_kaggle_file(root: Path, name: str) -> Path:
    matches = list(root.rglob(name))
    if not matches:
        raise FileNotFoundError(f'Could not find {name} under {root}')
    return matches[0]


def _extract_zip_if_needed(zip_path: Path, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as zf:
        zf.extractall(output_dir)


def setup_kaggle_environment(config: Config) -> Tuple[Path, Path]:
    train_csv_zip = find_kaggle_file(config.kaggle_input_dir, 'training_solutions_rev1.zip')
    image_zip = find_kaggle_file(config.kaggle_input_dir, 'images_training_rev1.zip')

    _extract_zip_if_needed(train_csv_zip, config.kaggle_temp_dir)
    _extract_zip_if_needed(image_zip, config.kaggle_temp_dir)

    csv_path = find_kaggle_file(config.kaggle_temp_dir, 'training_solutions_rev1.csv')
    image_dir = find_kaggle_file(config.kaggle_temp_dir, 'images_training_rev1')

    jpg_count = len(list(Path(image_dir).glob('*.jpg')))
    if jpg_count < 1000:
        raise RuntimeError(f'Expected >=1000 jpg files, found {jpg_count} in {image_dir}')

    return Path(csv_path), Path(image_dir)


def save_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2, default=str)


def is_kaggle_runtime() -> bool:
    return os.environ.get('KAGGLE_KERNEL_RUN_TYPE') is not None


# ══════════════════════════════════════════════════════════════
# V25 — GRADIENT ACCUMULATION HELPER
# ══════════════════════════════════════════════════════════════

class GradientAccumulationModel(tf.keras.Model):
    """Wrapper model that accumulates gradients over N mini-batches
    before applying an optimizer step. This allows effective large
    batch sizes when VRAM is limited (e.g., batch_size=16 × accum=2 = 32 effective).

    Usage:
        ga_model = GradientAccumulationModel(base_model, accumulation_steps=2)
        ga_model.compile(optimizer=..., loss=..., metrics=...)
        ga_model.fit(train_ds, ...)
    """

    def __init__(self, inner_model: tf.keras.Model, accumulation_steps: int = 2, **kwargs):
        super().__init__(**kwargs)
        self.inner_model = inner_model
        self.accumulation_steps = accumulation_steps
        self.step_count = tf.Variable(0, trainable=False, dtype=tf.int32)
        self._accum_gradients = None

    def call(self, inputs, training=False):
        return self.inner_model(inputs, training=training)

    @property
    def trainable_variables(self):
        return self.inner_model.trainable_variables

    def train_step(self, data):
        if len(data) == 3:
            x, y, sample_weight = data
        else:
            x, y = data
            sample_weight = None

        # Initialize gradient accumulators on first call
        if self._accum_gradients is None:
            self._accum_gradients = [
                tf.Variable(tf.zeros_like(v), trainable=False)
                for v in self.inner_model.trainable_variables
            ]

        with tf.GradientTape() as tape:
            y_pred = self.inner_model(x, training=True)
            loss = self.compiled_loss(y, y_pred, sample_weight=sample_weight)
            # Scale loss for accumulation
            scaled_loss = loss / tf.cast(self.accumulation_steps, tf.float32)

        gradients = tape.gradient(scaled_loss, self.inner_model.trainable_variables)

        # Accumulate
        for accum, grad in zip(self._accum_gradients, gradients):
            if grad is not None:
                accum.assign_add(grad)

        self.step_count.assign_add(1)

        # Apply when accumulation is complete
        tf.cond(
            tf.equal(self.step_count % self.accumulation_steps, 0),
            lambda: self._apply_and_reset(),
            lambda: None,
        )

        # Update metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight=sample_weight)
        return {m.name: m.result() for m in self.metrics}

    def _apply_and_reset(self):
        self.optimizer.apply_gradients(
            zip(self._accum_gradients, self.inner_model.trainable_variables)
        )
        for accum in self._accum_gradients:
            accum.assign(tf.zeros_like(accum))


# ══════════════════════════════════════════════════════════════
# V25 — LAYER-WISE LEARNING RATE DECAY (LLRD)
# ══════════════════════════════════════════════════════════════

def build_llrd_optimizer(
    model: tf.keras.Model,
    base_lr: float,
    decay_factor: float = 0.75,
    clipnorm: float = 1.0,
) -> tf.keras.optimizers.Adam:
    """Build an Adam optimizer with layer-wise learning rate decay (LLRD).

    Deeper (earlier) layers get exponentially lower learning rates.
    This prevents catastrophic forgetting of pre-trained features while
    allowing the head layers to adapt aggressively.

    For TF2/Keras, we implement this using a single optimizer with per-variable
    learning rate scaling via optimizer.build() and custom LR multipliers,
    simplified as grouped parameter approach.

    In practice, we use a simple 3-group approach:
      - Head layers (custom dense/BN): base_lr
      - Top backbone layers (unfrozen): base_lr × decay_factor
      - Lower backbone layers (if unfrozen): base_lr × decay_factor^2

    Args:
        model: The full model (head + backbone)
        base_lr: Learning rate for head layers
        decay_factor: Multiplicative decay per depth group
        clipnorm: Gradient clipping norm

    Returns:
        Configured Adam optimizer
    """
    # For Keras 3.x / TF 2.16+, use the standard Adam with gradient clipping
    # LLRD is approximated by setting per-layer trainable status and
    # using different LR schedules during training phases.
    # The actual per-variable LR in TF2 requires tf.keras.optimizers.legacy.Adam
    # which is deprecated. Instead, we rely on progressive unfreezing which
    # achieves a similar effect: earlier unfrozen layers have already been
    # fine-tuned at lower LR in earlier phases.

    optimizer = tf.keras.optimizers.Adam(
        learning_rate=base_lr,
        clipnorm=clipnorm,
    )
    return optimizer


def build_cosine_restart_schedule(
    initial_lr: float,
    steps_per_epoch: int,
    restart_epochs: int = 5,
    t_mul: float = 1.5,
    m_mul: float = 0.9,
    alpha: float = 1e-7,
) -> tf.keras.optimizers.schedules.LearningRateSchedule:
    """Build a cosine annealing schedule with warm restarts (SGDR).

    Warm restarts allow the model to escape local minima in complex
    loss landscapes (like the spiral/irregular boundary).
    """
    first_decay_steps = steps_per_epoch * restart_epochs
    schedule = tf.keras.optimizers.schedules.CosineDecayRestarts(
        initial_learning_rate=initial_lr,
        first_decay_steps=first_decay_steps,
        t_mul=t_mul,
        m_mul=m_mul,
        alpha=alpha,
    )
    return schedule


# ══════════════════════════════════════════════════════════════
# V25 — SWA HELPER
# ══════════════════════════════════════════════════════════════

def run_swa(
    model: tf.keras.Model,
    train_ds: tf.data.Dataset,
    swa_epochs: int = 5,
    swa_lr_high: float = 1e-5,
    swa_lr_low: float = 5e-6,
) -> tf.keras.Model:
    """Apply Stochastic Weight Averaging to an already-trained model.

    SWA averages multiple checkpoints from a cyclical LR schedule,
    producing a model in a wider minimum with better generalization.
    Consistently adds +0.5-1.5% accuracy on fine-grained classification.

    After averaging, runs a BN update pass to recalculate batch
    normalization statistics for the averaged weights.
    """
    print('\n[SWA] Starting Stochastic Weight Averaging...')

    swa_weights = None
    n_snapshots = 0

    for epoch in range(swa_epochs):
        # Cyclical LR between swa_lr_high and swa_lr_low
        cycle_lr = float(swa_lr_low + (swa_lr_high - swa_lr_low) * (1 + np.cos(np.pi * epoch / swa_epochs)) / 2)

        # Recompile to safely update learning rate (bypasses Keras 3 issues with schedule objects)
        model.compile(
            optimizer=tf.keras.optimizers.Adam(learning_rate=cycle_lr, clipnorm=1.0),
            loss=model.loss,
        )

        model.fit(train_ds, epochs=1, verbose=0)
        print(f'  SWA epoch {epoch + 1}/{swa_epochs} | LR: {cycle_lr:.2e}')

        # Accumulate weights (running average)
        current_weights = [w.numpy() for w in model.weights]
        if swa_weights is None:
            swa_weights = [w.copy() for w in current_weights]
        else:
            for i in range(len(swa_weights)):
                swa_weights[i] = (swa_weights[i] * n_snapshots + current_weights[i]) / (n_snapshots + 1)
        n_snapshots += 1

    # Apply averaged weights
    for w, swa_w in zip(model.weights, swa_weights):
        w.assign(swa_w)

    # BN update pass (required after SWA weight averaging)
    print('  [SWA] Running BN statistics update...')
    bn_update_steps = 0
    for x_batch in train_ds:
        if isinstance(x_batch, tuple):
            x = x_batch[0]
        else:
            x = x_batch
        model(x, training=True)
        bn_update_steps += 1
        if bn_update_steps >= 50:
            break

    print(f'  [SWA] Complete. Averaged {n_snapshots} snapshots.')
    return model


# ============================================================
# START OF losses.py
# ============================================================


@tf.keras.utils.register_keras_serializable(package="Custom")
def rmse_metric(y_true, y_pred):
    """Root Mean Squared Error for the 37 regression targets."""
    mse = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)
    return tf.maximum(0.0, tf.sqrt(mse))

@tf.keras.utils.register_keras_serializable(package="Custom")
class RMSELoss(tf.keras.losses.Loss):
    """Direct RMSE loss function instead of standard MSE.

    Can be used directly to optimize against the Kaggle LB metric.
    Includes a small epsilon inside the square root for numerical stability.
    """
    def __init__(self, name="rmse_loss", **kwargs):
        super().__init__(name=name, **kwargs)

    def call(self, y_true, y_pred):
        # Calculate MSE across the 37 features
        mse = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)
        # Apply sqrt with epsilon to prevent infinite gradient at exactly 0.0 variance
        return tf.sqrt(tf.maximum(mse, tf.keras.backend.epsilon()))

    def get_config(self):
        return super().get_config()


# ============================================================
# START OF model.py
# ============================================================




def _get_backbone(architecture: str, input_tensor: tf.Tensor) -> tf.keras.Model:
    """Instantiate a backbone model by architecture name with ImageNet weights."""
    arch_map = {
        'EfficientNetV2B0': tf.keras.applications.EfficientNetV2B0,
        'EfficientNetV2B1': tf.keras.applications.EfficientNetV2B1,
        'EfficientNetV2B2': tf.keras.applications.EfficientNetV2B2,
        'ConvNeXtTiny': tf.keras.applications.ConvNeXtTiny,
    }
    if architecture not in arch_map:
        raise ValueError(
            f'Unsupported architecture: {architecture}. '
            f'Available: {list(arch_map.keys())}'
        )
    return arch_map[architecture](
        include_top=False,
        weights='imagenet',
        input_tensor=input_tensor,
    )


def build_regression_model(
    architecture: str = 'EfficientNetV2B2',
) -> tuple[tf.keras.Model, tf.keras.Model]:
    """Build unified regression model: Predicts all 37 Galaxy Zoo probabilities.

    Architecture: backbone → GAP → BN → Dense(512) → BN → GELU →
                  Dropout(0.4) → Dense(37, sigmoid)

    Using Sigmoid on the final layer logically bounds all voting fractions to [0.0, 1.0].

    Returns:
        (full_model, base_model) tuple for progressive unfreezing.
    """
    inputs = tf.keras.Input(shape=(None, None, 3), name='image_input')
    base_model = _get_backbone(architecture, inputs)

    x = tf.keras.layers.GlobalAveragePooling2D(name='gap')(base_model.output)
    x = tf.keras.layers.BatchNormalization(name='bn1')(x)
    x = tf.keras.layers.Dense(512, name='dense1')(x)
    x = tf.keras.layers.BatchNormalization(name='bn2')(x)
    x = tf.keras.layers.Activation('gelu', name='gelu1')(x)
    x = tf.keras.layers.Dropout(0.4, name='dropout1')(x)

    # 37 dimensional output bounded to [0, 1] interval natively using sigmoid
    outputs = tf.keras.layers.Dense(
        37, activation='sigmoid', dtype='float32', name='regression_output'
    )(x)

    model = tf.keras.Model(
        inputs=inputs, outputs=outputs,
        name=f'GalaxyNet_UnifiedRegression_{architecture}',
    )
    return model, base_model


def unfreeze_top_layers(base_model: tf.keras.Model, last_n: int) -> int:
    """Gradually unfreezes the last N layers of the base model for fine-tuning.

    All layers before the last N are frozen (not trainable).
    Returns the number of unfrozen layers (those with trainable weights).
    """
    base_model.trainable = True
    total_layers = len(base_model.layers)
    freeze_up_to = max(0, total_layers - last_n)
    for layer in base_model.layers[:freeze_up_to]:
        layer.trainable = False
    # Unfreeze everything after the boundary
    for layer in base_model.layers[freeze_up_to:]:
        layer.trainable = True
    # Count layers that are actually trainable and have weights
    unfrozen = sum(1 for l in base_model.layers[freeze_up_to:] if len(l.weights) > 0)
    return unfrozen


def freeze_base(base_model: tf.keras.Model) -> None:
    """Freeze all layers of the base model (for warmup phase)."""
    base_model.trainable = False


# ============================================================
# START OF dataset.py
# ============================================================







# ══════════════════════════════════════════════════════════════
# LABEL DETERMINATION (Regression - 37 Targets)
# ══════════════════════════════════════════════════════════════

def generate_labels_df(solutions_csv: Path, image_dir: Path) -> pd.DataFrame:
    """Generate 37-target DataFrame from Galaxy Zoo solutions CSV for Regression."""
    df = pd.read_csv(solutions_csv)

    # Automatically extract all 37 Class probability columns
    target_cols = [col for col in df.columns if col.startswith('Class')]
    if len(target_cols) != 37:
        print(f"WARNING: Expected 37 Class columns, found {len(target_cols)}")

    df['image_path'] = df['GalaxyID'].astype(str).apply(lambda gid: str(image_dir / f'{gid}.jpg'))

    # Check physical file existence to prune missing downloads
    df = df[df['image_path'].apply(lambda p: Path(p).exists())].copy()

    keep_cols = ['image_path'] + target_cols
    return df[keep_cols], target_cols


# ══════════════════════════════════════════════════════════════
# IMAGE LOADING & BASE PREPROCESSING
# ══════════════════════════════════════════════════════════════

def _center_crop(image: tf.Tensor, ratio: float = 0.75) -> tf.Tensor:
    h = tf.shape(image)[0]
    w = tf.shape(image)[1]
    ch = tf.cast(tf.cast(h, tf.float32) * ratio, tf.int32)
    cw = tf.cast(tf.cast(w, tf.float32) * ratio, tf.int32)
    offset_h = (h - ch) // 2
    offset_w = (w - cw) // 2
    return tf.image.crop_to_bounding_box(image, offset_h, offset_w, ch, cw)


def load_and_preprocess_image(path: tf.Tensor, label: tf.Tensor, image_size: int,
                               center_crop_ratio: float = 0.75):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.cast(img, tf.float32)
    img = _center_crop(img, ratio=center_crop_ratio)
    img = tf.image.resize(img, [image_size, image_size])
    img = tf.clip_by_value(img, 0.0, 255.0)
    return img, label


# ══════════════════════════════════════════════════════════════
# AUGMENTATION
# ══════════════════════════════════════════════════════════════

def apply_cutout(image: tf.Tensor, n_holes: int = 2, max_size_ratio: float = 0.20) -> tf.Tensor:
    shape = tf.shape(image)
    h, w = shape[0], shape[1]
    img_mean = tf.reduce_mean(image)

    mask = tf.ones_like(image)
    for _ in range(n_holes):
        hole_size_h = tf.random.uniform([], minval=tf.cast(tf.cast(h, tf.float32) * 0.05, tf.int32),
                                         maxval=tf.maximum(tf.cast(tf.cast(h, tf.float32) * max_size_ratio, tf.int32), 2),
                                         dtype=tf.int32)
        hole_size_w = tf.random.uniform([], minval=tf.cast(tf.cast(w, tf.float32) * 0.05, tf.int32),
                                         maxval=tf.maximum(tf.cast(tf.cast(w, tf.float32) * max_size_ratio, tf.int32), 2),
                                         dtype=tf.int32)
        cy = tf.random.uniform([], minval=hole_size_h // 2, maxval=h - hole_size_h // 2, dtype=tf.int32)
        cx = tf.random.uniform([], minval=hole_size_w // 2, maxval=w - hole_size_w // 2, dtype=tf.int32)

        y1 = tf.maximum(cy - hole_size_h // 2, 0)
        y2 = tf.minimum(cy + hole_size_h // 2, h)
        x1 = tf.maximum(cx - hole_size_w // 2, 0)
        x2 = tf.minimum(cx + hole_size_w // 2, w)

        top_pad = y1
        bottom_pad = h - y2
        left_pad = x1
        right_pad = w - x2
        hole_h = y2 - y1
        hole_w = x2 - x1

        hole = tf.zeros([hole_h, hole_w, 3])
        hole = tf.pad(hole, [[top_pad, bottom_pad], [left_pad, right_pad], [0, 0]], constant_values=1.0)
        mask = mask * hole

    image = image * mask + img_mean * (1.0 - mask)
    return image


def apply_poisson_noise(image: tf.Tensor, scale: float = 25.0) -> tf.Tensor:
    img_norm = image / 255.0
    img_scaled = img_norm * scale
    noisy = tf.random.poisson(shape=[], lam=tf.maximum(img_scaled, 1e-6))
    noisy = noisy / scale * 255.0
    return tf.clip_by_value(noisy, 0.0, 255.0)


def apply_gaussian_blur(image: tf.Tensor, sigma: float = 1.0) -> tf.Tensor:
    kernel_size = tf.cast(tf.math.ceil(sigma * 3.0) * 2 + 1, tf.int32)
    kernel_size = tf.maximum(kernel_size, 3)
    half = tf.cast(kernel_size // 2, tf.float32)
    x = tf.range(-half, half + 1, dtype=tf.float32)
    kernel_1d = tf.exp(-x ** 2 / (2.0 * sigma ** 2))
    kernel_1d = kernel_1d / tf.reduce_sum(kernel_1d)
    kernel_2d = tf.tensordot(kernel_1d, kernel_1d, axes=0)
    kernel_2d = kernel_2d[:, :, tf.newaxis, tf.newaxis]
    kernel_2d = tf.tile(kernel_2d, [1, 1, 3, 1])

    image_4d = tf.expand_dims(image, 0)
    blurred = tf.nn.depthwise_conv2d(image_4d, kernel_2d, strides=[1, 1, 1, 1], padding='SAME')
    return tf.squeeze(blurred, 0)


def apply_continuous_rotation(image: tf.Tensor) -> tf.Tensor:
    if tfa is not None:
        angle = tf.random.uniform([], 0.0, 2.0 * math.pi)
        return tfa.image.rotate(image, angle, interpolation='BILINEAR')
    else:
        angle = tf.random.uniform([], 0.0, 2.0 * math.pi)
        cos_a = tf.cos(angle)
        sin_a = tf.sin(angle)
        h = tf.cast(tf.shape(image)[0], tf.float32)
        w = tf.cast(tf.shape(image)[1], tf.float32)
        cx, cy = w / 2.0, h / 2.0
        a2 = cx - cx * cos_a - cy * sin_a
        b2 = cy + cx * sin_a - cy * cos_a
        transform = [cos_a, sin_a, a2, -sin_a, cos_a, b2, 0.0, 0.0]
        transform = tf.cast(tf.stack(transform), tf.float32)
        transform = tf.reshape(transform, [1, 8])
        image_4d = tf.expand_dims(image, 0)
        rotated = tf.raw_ops.ImageProjectiveTransformV3(
            images=image_4d,
            transforms=transform,
            output_shape=tf.shape(image)[:2],
            fill_value=0.0,
            interpolation='BILINEAR',
            fill_mode='REFLECT',
        )
        return tf.squeeze(rotated, 0)


def augment_image(image: tf.Tensor, label: tf.Tensor):
    shape = tf.shape(image)
    orig_h, orig_w = shape[0], shape[1]

    image = apply_continuous_rotation(image)
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)

    if tf.random.uniform([]) < 0.3:
        image = apply_poisson_noise(image, scale=25.0)

    if tf.random.uniform([]) < 0.2:
        sigma = tf.random.uniform([], 0.5, 2.0)
        image = apply_gaussian_blur(image, sigma)

    if tf.random.uniform([]) > 0.5:
        image = tf.image.random_brightness(image, max_delta=0.15 * 255.0)
        image = tf.image.random_contrast(image, lower=0.85, upper=1.15)

    crop_h = tf.cast(tf.cast(orig_h, tf.float32) * 0.9, tf.int32)
    crop_w = tf.cast(tf.cast(orig_w, tf.float32) * 0.9, tf.int32)
    image = tf.image.random_crop(image, [crop_h, crop_w, 3])
    image = tf.image.resize(image, [orig_h, orig_w])

    if tf.random.uniform([]) > 0.7:
        image = apply_cutout(image, n_holes=1, max_size_ratio=0.15)

    image = tf.clip_by_value(image, 0.0, 255.0)
    return image, label


# ══════════════════════════════════════════════════════════════
# DATASET BUILDERS
# ══════════════════════════════════════════════════════════════

def build_dataset(
    image_paths: np.ndarray,
    labels: np.ndarray,
    image_size: int,
    batch_size: int,
    center_crop_ratio: float = 0.75,
    augment: bool = False,
    shuffle: bool = False,
    cache: bool = False,
) -> tf.data.Dataset:
    """Build a tf.data.Dataset mapping paths and 37-node target vectors."""
    ds = tf.data.Dataset.from_tensor_slices((image_paths, labels))
    ds = ds.map(
        lambda p, y: load_and_preprocess_image(p, y, image_size, center_crop_ratio),
        num_parallel_calls=tf.data.AUTOTUNE,
    )

    if shuffle:
        ds = ds.shuffle(buffer_size=min(len(image_paths), 10000), reshuffle_each_iteration=True)

    if augment:
        ds = ds.map(lambda i, l: augment_image(i, l), num_parallel_calls=tf.data.AUTOTUNE)

    if cache:
        ds = ds.cache()

    ds = ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return ds


# ══════════════════════════════════════════════════════════════
# SPLITTING & ORCHESTRATION
# ══════════════════════════════════════════════════════════════

def build_datasets(labels_df: pd.DataFrame, config: Config):
    """Split data randomly for regression."""
    train_df, temp_df = train_test_split(
        labels_df,
        test_size=config.val_split + config.test_split,
        random_state=config.seed,
    )
    test_ratio_of_temp = config.test_split / (config.val_split + config.test_split)
    val_df, test_df = train_test_split(
        temp_df,
        test_size=test_ratio_of_temp,
        random_state=config.seed,
    )

    train_df = train_df.reset_index(drop=True)
    val_df = val_df.reset_index(drop=True)
    test_df = test_df.reset_index(drop=True)

    split_info = {
        'train_size': len(train_df),
        'val_size': len(val_df),
        'test_size': len(test_df),
        'total_labeled_images': len(labels_df),
    }

    return split_info, (train_df, val_df, test_df)


# ============================================================
# START OF stacking.py
# ============================================================






def _build_feature_extractor(model: tf.keras.Model) -> tf.keras.Model:
    """Create a headless version of a trained model that outputs feature vectors.

    Removes the final Dense(1, sigmoid) output layer and returns the model
    that outputs the penultimate layer's features (before the classification head).
    """
    # Find the last Dense layer and use the layer before it as output
    for i in range(len(model.layers) - 1, -1, -1):
        layer = model.layers[i]
        if isinstance(layer, tf.keras.layers.Dense) and layer.output_shape[-1] == 1:
            # Found the classification head — use the previous layer's output
            feature_output = model.layers[i - 1].output
            return tf.keras.Model(inputs=model.input, outputs=feature_output)

    # Fallback: use the second-to-last layer
    return tf.keras.Model(inputs=model.input, outputs=model.layers[-2].output)


def extract_features(
    model_paths: list[str],
    df: pd.DataFrame,
    config: Config,
    batch_size: int = 32,
) -> np.ndarray:
    """Extract deep features from multiple models and concatenate them.

    For each model, removes the classification head and passes all images
    through the backbone + intermediate layers to get feature vectors.
    The features from all models are concatenated horizontally.

    Args:
        model_paths: Paths to trained Keras models.
        df: DataFrame with 'image_path' column.
        config: Training config.
        batch_size: Batch size for feature extraction.

    Returns:
        features: np.ndarray of shape (n_samples, total_feature_dim)
    """
    paths = df['image_path'].astype(str).to_numpy()
    image_size = config.image_size_phase3
    dummy_labels = np.zeros(len(paths), dtype=np.float32)

    all_features = []
    custom_objects = {
        'BinaryFocalLoss': BinaryFocalLoss,
        'OHEMBinaryLoss': OHEMBinaryLoss,
    }

    for model_path in model_paths:
        print(f'  Extracting features from: {model_path}')
        model = tf.keras.models.load_model(model_path, custom_objects=custom_objects)
        extractor = _build_feature_extractor(model)

        ds = build_dataset(
            paths, dummy_labels, image_size, batch_size,
            center_crop_ratio=config.center_crop_ratio,
        )

        features = extractor.predict(ds, verbose=0)
        all_features.append(features)

        # Cleanup
        del model, extractor
        tf.keras.backend.clear_session()

    # Concatenate features from all models: (n_samples, dim1 + dim2 + ...)
    concatenated = np.concatenate(all_features, axis=1)
    print(f'  Total feature dimension: {concatenated.shape[1]}')
    return concatenated


def train_xgboost_stacker(
    train_features: np.ndarray,
    train_labels: np.ndarray,
    val_features: np.ndarray,
    val_labels: np.ndarray,
    config: Config,
    output_path: Path,
) -> object:
    """Train an XGBoost classifier on extracted deep features.

    Uses the concatenated feature vectors from multiple CNN/Transformer
    backbones to learn non-linear decision boundaries that simple
    averaging or thresholding cannot capture.

    Args:
        train_features: Training features from extract_features().
        train_labels: Integer class labels (0=spiral, 1=elliptical, 2=irregular).
        val_features: Validation features.
        val_labels: Validation integer class labels.
        config: Training config with XGBoost hyperparameters.
        output_path: Path to save the trained model.

    Returns:
        Trained XGBoost classifier.
    """
    try:
        import xgboost as xgb
    except ImportError:
        print('WARNING: xgboost not available. Installing...')
        import subprocess
        subprocess.check_call(['pip', 'install', 'xgboost', '-q'])
        import xgboost as xgb

    # Compute sample weights for class imbalance
    class_counts = np.bincount(train_labels, minlength=3)
    total = len(train_labels)
    class_weights = total / (3.0 * class_counts + 1e-8)
    sample_weights = np.array([class_weights[label] for label in train_labels])

    print(f'\n[XGBoost Stacker] Training on {train_features.shape[0]} samples, '
          f'{train_features.shape[1]} features...')
    print(f'  Class distribution: {dict(zip(CLASS_NAMES, class_counts))}')

    clf = xgb.XGBClassifier(
        n_estimators=config.xgb_n_estimators,
        max_depth=config.xgb_max_depth,
        learning_rate=config.xgb_learning_rate,
        objective='multi:softprob',
        num_class=3,
        eval_metric='mlogloss',
        use_label_encoder=False,
        tree_method='hist',      # Fast histogram-based method
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,           # L1 regularization
        reg_lambda=1.0,          # L2 regularization
        random_state=config.seed,
        verbosity=0,
    )

    clf.fit(
        train_features, train_labels,
        sample_weight=sample_weights,
        eval_set=[(val_features, val_labels)],
        verbose=False,
    )

    # Evaluate on validation set
    val_preds = clf.predict(val_features)
    val_acc = float(np.mean(val_preds == val_labels))
    print(f'  XGBoost val accuracy: {val_acc:.4f}')

    # Save model
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'wb') as f:
        pickle.dump(clf, f)
    print(f'  Model saved to: {output_path}')

    return clf


def predict_with_stacker(
    clf,
    features: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Run XGBoost stacker prediction.

    Args:
        clf: Trained XGBoost classifier.
        features: Feature vectors from extract_features().

    Returns:
        predictions: Integer class predictions.
        probabilities: Class probability matrix (n_samples, 3).
    """
    probabilities = clf.predict_proba(features)
    predictions = clf.predict(features)
    return predictions.astype(np.int32), probabilities


def load_stacker(model_path: Path):
    """Load a saved XGBoost stacker from disk."""
    with open(model_path, 'rb') as f:
        return pickle.load(f)


# ============================================================
# START OF evaluate.py
# ============================================================



from tqdm import tqdm



def calculate_rmse(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """Calculate the global Root Mean Squared Error over all targets."""
    mse = np.mean(np.square(y_true - y_pred))
    return np.sqrt(mse)


def predict_tta(model: tf.keras.Model, test_paths: np.ndarray, config: Config) -> np.ndarray:
    """Run Test-Time Augmentation (TTA) and return averaged predictions."""
    print(f"\n[Evaluation] Running TTA ({config.tta_n_augments} passes)...")

    # Dummy labels for the dataset builder
    dummy_labels = np.zeros((len(test_paths), 37), dtype=np.float32)

    tta_preds = []

    # Pass 1: Original (unaugmented) center crop
    ds_base = build_dataset(
        test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
    )
    base_preds = model.predict(ds_base, verbose=1)
    tta_preds.append(base_preds)

    # Passes 2 to N: Augmented crops/rotations
    for i in range(config.tta_n_augments - 1):
        ds_aug = build_dataset(
            test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
            center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=False,
        )
        preds = model.predict(ds_aug, verbose=0)
        tta_preds.append(preds)
        print(f"  TTA pass {i+2}/{config.tta_n_augments} completed.")

    return np.mean(tta_preds, axis=0)


def evaluate_regression(config: Config, test_df: pd.DataFrame, target_cols: list[str]):
    """Evaluate the single unified regression model using RMSE."""
    output_dir = config.output_dir
    model_path = output_dir / 'unified_best.keras'

    if not model_path.exists():
        print(f"Error: Unified model not found at {model_path}")
        return

    print('\n' + '=' * 60)
    print('EVALUATION: REGRESSION RMSE')
    print('=' * 60)

    # Load model
    print("Loading unified model...")
    custom_objects = {
        'RMSELoss': RMSELoss,
        'rmse_metric': rmse_metric,
    }
    model = tf.keras.models.load_model(model_path, custom_objects=custom_objects)

    test_paths = test_df['image_path'].values
    y_true = test_df[target_cols].values.astype(np.float32)

    # Standard Prediction (No TTA)
    dummy_labels = np.zeros_like(y_true)
    ds_test = build_dataset(
        test_paths, dummy_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
    )

    print("\nRunning standard evaluation (1-pass)...")
    y_pred_std = model.predict(ds_test, verbose=1)
    rmse_std = calculate_rmse(y_true, y_pred_std)

    # TTA Prediction
    y_pred_tta = predict_tta(model, test_paths, config)
    rmse_tta = calculate_rmse(y_true, y_pred_tta)

    # Report
    print('\n' + '-' * 40)
    print("TEST METRICS (Kaggle Leaderboard Objective)")
    print('-' * 40)
    print(f"  RMSE (Single Pass): {rmse_std:.5f}")
    print(f"  RMSE (TTA {config.tta_n_augments}x):     {rmse_tta:.5f}")
    print('-' * 40)

    # Save results
    results = {
        'test_size': len(test_df),
        'rmse_standard': float(rmse_std),
        'rmse_tta': float(rmse_tta),
    }

    with open(output_dir / 'evaluation_results.json', 'w') as f:
        json.dump(results, f, indent=2)

    print(f"\nEvaluation complete. Results saved to {output_dir / 'evaluation_results.json'}")


# ============================================================
# START OF train.py
# ============================================================




if os.environ.get('KAGGLE_KERNEL_RUN_TYPE'):
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))



class ConciseLogging(tf.keras.callbacks.Callback):
    """Minimal epoch-end logging to keep Kaggle notebook output clean."""
    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}
        msg = (
            f"Epoch {epoch + 1:03d} | "
            f"loss: {logs.get('loss', 0):.4f} | "
            f"rmse: {logs.get('rmse_metric', 0):.4f} | "
            f"val_loss: {logs.get('val_loss', 0):.4f} | "
            f"val_rmse: {logs.get('val_rmse_metric', 0):.4f}"
        )
        print(msg)


def train_unified_regression(config: Config, solutions_csv: Path, image_dir: Path):
    """Train single 37-node regression model using progressive resizing."""

    set_global_seed(config.seed)
    if config.enable_mixed_precision:
        tf.keras.mixed_precision.set_global_policy('mixed_float16')

    df, target_cols = generate_labels_df(solutions_csv, image_dir)
    print(f"Loaded {len(df)} images with {len(target_cols)} regression targets.")

    split_info, (train_df, val_df, test_df) = build_datasets(df, config)

    train_paths = train_df['image_path'].values
    train_labels = train_df[target_cols].values.astype(np.float32)
    val_paths = val_df['image_path'].values
    val_labels = val_df[target_cols].values.astype(np.float32)

    # 2. Build Model
    model, base_model = build_regression_model(architecture=config.architecture)

    output_dir = config.output_dir
    os.makedirs(output_dir, exist_ok=True)

    print('\n' + '=' * 60)
    print(f'TRAINING REGRESSION MODEL ({config.architecture})')
    print('=' * 60)

    loss_fn = RMSELoss()

    # ── Phase 1: Warmup @ 128px ──
    print(f'\n[Phase 1] Warmup @ {config.image_size_phase1}px (frozen backbone)')
    freeze_base(base_model)

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase1, config.batch_size_phase1,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase1, config.batch_size_phase1,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=False,
    )

    model.compile(
        optimizer=tf.keras.optimizers.Adam(config.warmup_lr, clipnorm=1.0),
        loss=loss_fn,
        metrics=[rmse_metric],
    )

    h1 = model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.warmup_epochs,
        callbacks=[
            tf.keras.callbacks.ModelCheckpoint(
                str(output_dir / 'phase1.keras'),
                monitor='val_rmse_metric', save_best_only=True, mode='min',
            ),
            ConciseLogging(),
        ],
        verbose=0,
    )

    # ── Phase 2: Mid-tune @ 192px ──
    print(f'\n[Phase 2] Mid-tune @ {config.image_size_phase2}px (unfreeze {config.unfreeze_phase2} layers)')
    n_unfrozen = unfreeze_top_layers(base_model, config.unfreeze_phase2)
    print(f'  Unfrozen layers: {n_unfrozen}')

    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase2, config.batch_size_phase2,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase2, config.batch_size_phase2,
        center_crop_ratio=config.center_crop_ratio,
    )

    lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
        config.midtune_lr, decay_steps=config.midtune_epochs * (len(train_paths) // config.batch_size_phase2)
    )
    model.compile(
        optimizer=tf.keras.optimizers.Adam(lr_schedule, clipnorm=1.0),
        loss=loss_fn, metrics=[rmse_metric],
    )

    h2 = model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.midtune_epochs,
        callbacks=[
            tf.keras.callbacks.ModelCheckpoint(
                str(output_dir / 'phase2.keras'),
                monitor='val_rmse_metric', save_best_only=True, mode='min',
            ),
            ConciseLogging(),
        ],
        verbose=0,
    )

    # ── Phase 3: Full fine-tune @ 288px ──
    print(f'\n[Phase 3] Full fine-tune @ {config.image_size_phase3}px (unfreeze {config.unfreeze_phase3} layers)')
    n_unfrozen = unfreeze_top_layers(base_model, config.unfreeze_phase3)

    # Use Gradient Accumulation if batch size is small
    train_ds = build_dataset(
        train_paths, train_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=True, shuffle=True,
    )
    val_ds = build_dataset(
        val_paths, val_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio,
    )

    steps_per_epoch = len(train_paths) // config.batch_size_phase3
    lr_schedule_p3 = build_cosine_restart_schedule(
        config.finetune_lr, steps_per_epoch, restart_epochs=5, t_mul=1.5, m_mul=0.9
    )

    active_model = model
    if config.grad_accumulation_steps > 1:
        active_model = GradientAccumulationModel(model, config.grad_accumulation_steps)

    active_model.compile(
        optimizer=tf.keras.optimizers.Adam(lr_schedule_p3, clipnorm=1.0),
        loss=loss_fn, metrics=[rmse_metric],
    )

    h3 = active_model.fit(
        train_ds, validation_data=val_ds,
        epochs=config.finetune_epochs,
        callbacks=[
            tf.keras.callbacks.ModelCheckpoint(
                str(output_dir / 'unified_best.keras'),
                monitor='val_rmse_metric', save_best_only=True, mode='min',
            ),
            ConciseLogging(),
        ],
        verbose=0,
    )

    # ── SWA ──
    print('\n[SWA Phase]')
    train_ds_swa = build_dataset(
        train_paths, train_labels, config.image_size_phase3, config.batch_size_phase3,
        center_crop_ratio=config.center_crop_ratio, augment=False, shuffle=True,
    )
    model = run_swa(model, train_ds_swa, config.swa_epochs, config.swa_lr_high, config.swa_lr_low)
    model.save(str(output_dir / 'unified_best.keras'))

    # Save details
    save_json(split_info, output_dir / 'split_info.json')

    # Cleanup
    tf.keras.backend.clear_session()
    gc.collect()

    return test_df, target_cols


def main():
    t0 = time.time()
    config = Config()

    if is_kaggle_runtime():
        print("Running in Kaggle environment.")
        solutions_csv, image_dir = setup_kaggle_environment(config)
    else:
        print("Running in local/VM environment.")
        setup_environment(config)
        solutions_csv = Path("training_solutions_rev1.csv")
        image_dir = Path("images_training_rev1")

    # Pipeline
    test_df, target_cols = train_unified_regression(config, solutions_csv, image_dir)

    print(f"\nTraining pipeline completed in {(time.time() - t0) / 60:.1f} minutes.")

    # Run evaluation
    evaluate_regression(config, test_df, target_cols)


if __name__ == '__main__':
    main()
