import re
from pathlib import Path

# Order matters for dependencies — each module only depends on modules listed before it
MODULES = [
    'config.py',
    'utils.py',
    'losses.py',
    'model.py',
    'dataset.py',
    'evaluate.py',
    'train.py',
]

OUTPUT_FILE = 'train_kaggle_bundle.py'

# Modules whose imports are consolidated into the header
LOCAL_MODULES = {'config', 'utils', 'losses', 'model', 'dataset', 'evaluate', 'train'}

HEADER_MODULES = {
    'argparse', 'datetime', 'gc', 'json', 'math', 'multiprocessing',
    'os', 'random', 'sys', 'time', 'zipfile', 'dataclasses',
    'pathlib', 'typing',
    'matplotlib', 'numpy', 'np', 'pandas', 'pd', 'tensorflow', 'tf',
    'sklearn',
}


def _is_import_line(stripped: str) -> bool:
    """Check if a line is an import statement."""
    return stripped.startswith('import ') or stripped.startswith('from ')


def _get_import_module(stripped: str) -> str:
    """Extract the top-level module name from an import line."""
    if stripped.startswith('from '):
        parts = stripped.split()
        if len(parts) >= 2:
            return parts[1].split('.')[0]
    elif stripped.startswith('import '):
        parts = stripped.replace('import ', '').split(',')[0].split(' as ')[0].strip()
        return parts.split('.')[0]
    return ''


def consolidate():
    """Merge all modular Python files into a single Kaggle-compatible bundle."""
    header = '''# AUTO-GENERATED KAGGLE BUNDLE — GalaxyNet V25 Cascade Pipeline
# This file merges modular components for Kaggle compatibility.
# Generated by scripts/consolidate.py

from __future__ import annotations

import argparse
import datetime
import gc
import json
import math
import multiprocessing
import os
import random
import sys
import time
import zipfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Tuple

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import (
    brier_score_loss,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split

try:
    import tensorflow_addons as tfa
except Exception:
    tfa = None

'''

    output_lines = header.rstrip().split('\n')

    for filename in MODULES:
        file_path = Path(filename)
        if not file_path.exists():
            print(f"Warning: {filename} not found, skipping.")
            continue

        output_lines.append(f'\n# {"=" * 60}')
        output_lines.append(f'# START OF {filename}')
        output_lines.append(f'# {"=" * 60}\n')

        with open(file_path, 'r') as f:
            content = f.read()

        # Process line by line with multi-line import awareness
        lines = content.split('\n')
        i = 0
        while i < len(lines):
            line = lines[i]
            stripped = line.strip()

            # Skip __future__ imports
            if 'from __future__ import' in stripped:
                i += 1
                continue

            # Skip matplotlib.use (already in header)
            if stripped == "matplotlib.use('Agg')":
                i += 1
                continue

            # Detect try/except tensorflow_addons block
            if stripped == 'try:' and i + 1 < len(lines) and 'tensorflow_addons' in lines[i + 1]:
                # Skip until we find 'tfa = None' line
                while i < len(lines):
                    if 'tfa = None' in lines[i]:
                        i += 1
                        break
                    i += 1
                continue

            # Check if this is an import line
            if _is_import_line(stripped):
                mod = _get_import_module(stripped)

                # Is it a local module import?
                is_local = mod in LOCAL_MODULES

                # Is it already in the header?
                is_header = mod in HEADER_MODULES

                if is_local or is_header:
                    # Check if it's a multi-line import (ends with open paren and no close)
                    if '(' in stripped and ')' not in stripped:
                        # Skip entire multi-line import block until closing )
                        while i < len(lines) and ')' not in lines[i]:
                            i += 1
                        i += 1  # skip the line with )
                        continue
                    else:
                        # Single line import — skip it
                        i += 1
                        continue

            output_lines.append(line.rstrip() if line.rstrip() else '')
            i += 1

    # Write output
    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(output_lines))

    print(f"Successfully created {OUTPUT_FILE}")
    print(f"Total lines: {len(output_lines)}")


if __name__ == '__main__':
    consolidate()
